### ISSUE TITLE
Change ExceptionlessSendErrorsAttribute to be configurable

### ISSUE THREAD

**Issue by joelluijmes** [exceptionless/Exceptionless.Net#106]
Currently when using Exceptionless.Mvc it automatically registers the `ExceptionlessSendErrorsAttribute`, however I already have need for a `IExceptionFilter` and wanted to use Exceptionless from there. (There is some additional stuff that happens, creating a reference id.)

When the `ExceptionlessSendErrorsAttribute` executes first it conflicts with my custom filter. My request was to make this configurable, but that may be a bad design decision having a MVC setting in the core `ExceptionlessConfiguration`.

Another idea is to check if an `IExceptionFilter` already is in the filters, but that could interfere with other filters that don't use Exceptionless in there filter.

My last idea (and maybe the best) is to make `OnException(ExceptionContext)` virtual and letting users override it incase they need a different implementation. 

Any thoughts, ideas or don't you see need for such a change?

Here is how I use it now: https://github.com/joelluijmes/Exceptionless.Net/commit/e9542fa2f484447d3fb6daf50037b1bb2f277e33

**Comment by niemyjski** [comment]
We only check for an existing instance of `ExceptionlessSendErrorsAttribute`, if it's not there we add it. The problem if we make it virtual is that basically it's very very hard to ensure that if you inject your own instance in your own http module that it will be added before our module. So basically you don't know if your instance was picked up.

Also, there is not very much contextual data that you could add there that's not already there. If there's more we could add, let us know.

I think for what you want to do (reference ids). I'd call `ExceptionlessClient.Default.Configuration.UseReferenceIds()` on the very first line of your global application object / app builder. There is a chance that one or two errors may get thrown between when the http module gets hit and your startup code is called but all future instances will get reference ids. Please note you could also add a plugin as well!

I'm going to close this, but if you are not happy or need any help, please comment back to this issue and we will reopen it. Also, please feel free to join our slack: http://slack.exceptionless.com
