### ISSUE TITLE
Improved Xamarin support

### ISSUE THREAD

**Issue by MihaMarkic** [exceptionless/Exceptionless.Net#107]
I'm playing with Xamarin (PCL exceptionless) and seeing that everything not yet sent is lost if app crashes. Including the reason for app crashing.
I understand there is no file system in PCL, but this issue has to be addressed somehow. Perhaps through DI or something.

**Comment by MihaMarkic** [comment]
One workaround would be to call client.ProcessQueue(). This works better, but still, if there are problems like no network at the moment or OS decides to terminate the app regardless it won't work.

**Comment by MihaMarkic** [comment]
to continue my monologoue :)
I've copied FolderObjectStorage and implemented it at Xamarin level and it works nicely.
Should I create a pull request, anybody interested?

**Comment by MihaMarkic** [comment]
Added pull request #108

**Comment by niemyjski** [comment]
Folder object storage, wiring up to submit on process exit and app domain unhandled exception is available in FullFramework and .NET Standard 1.3+, can you only reference pcl packages currently in Xamarin?

**Comment by niemyjski** [comment]
Is it still a pain to build on appveyor (https://www.appveyor.com/docs/lang/xamarin) now that it's free?

I guess it doesn't support the new project format either from what I've read so it's tied to pcl which is kinda limited :\. I bet we can source import (add file link) the files we need to make this easier.

Some things I think we may want to support as well is hooking into platform specific events like app shut down + sleeping etc..

I'm going to create a new branch `feature/xamarin` can you resubmit the pr to that branch and we could work on both ios and android together :)

**Comment by MihaMarkic** [comment]
Sure. About referencing 4.5 or .netstandard. The former yields

> C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1408,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Perhaps it doesn't exist in the Mono for Android profile?

While xamarin just yesterday introduced support for .netstandard 1.6. However I tried with exceptionless .netstandard 1.3 and 1.5 but I ended up at can't load System.AppDomain.

Furthermore Directory.GetFiles doesn't like directory path as searchpattern.

**Comment by MihaMarkic** [comment]
PR resubmitted.

**Comment by niemyjski** [comment]
Thanks! If you want to work on ios as well that would be greatly appreciated. let me know when you want to merge in and I'll try and figure out the above error you were seeing. If we could reference net standard 1.5+ we basically wouldn't need more than a few platform specific hooks and we'd be done.

Also please feel free to join our slack http://slack.exceptionless.com

**Comment by niemyjski** [comment]
Looks like you have to have Xamarin 6.0.2 installed or newer otherwise it can't handle packages that contain .net standard assemblies.

I've also filed a bug here to try and get some help.. https://bugzilla.xamarin.com/show_bug.cgi?id=42786

As a short term work around: Currently, it looks like there is an issue with one of our .net standard dependencies and it causes install issues. It also seems that you need Xamarin 6.0.2 installed for things to work. But regardless, right now the short term solution is to download the package manually from nuget and reference the PCL package, then you'll need to manually wire up to event handlers as shown here: https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Extensions/ExceptionlessClientExtensions.cs#L31-L36 The handlers are defined at the bottom of the file, this is a short term work around.

**Comment by niemyjski** [comment]
https://github.com/dotnet/buildtools/issues/877

**Comment by niemyjski** [comment]
How is this working out for you?

**Comment by MihaMarkic** [comment]
It seems working, albeit it is a hassle installing exceptionless to xamarin (reference exceptionless package and then add manually a couple of nuget packages, i.e. System.AppDomain).
But I can certainly live with it.

**Comment by niemyjski** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=44700

**Comment by niemyjski** [comment]
@MihaMarkic  Are you able to install and compile on an iOS or android project? I can install on both but can't build (one is due to a signing cert and the other I'm blocked on https://bugzilla.xamarin.com/show_bug.cgi?id=44700). I'm just curious if you are.

**Comment by niemyjski** [comment]
I think I've resolved these issues in the latest stable release. Can you please try it and reopen this issue if you are still having issues.

**Comment by niemyjski** [comment]
Were pushing netstandard 2.0 release right now which should greatly help with this.
