### ISSUE TITLE
issue with .net core self-contained applications and System.IO.IsolatedStorage

### ISSUE THREAD

**Issue by otakusid** [exceptionless/Exceptionless.Net#111]
I try to install Exceptionless in **.net core self-contained** application and receive error in process of NuGet packages restoring:

```
System.IO.IsolatedStorage 4.0.1 provides a compile-time reference assembly for System.IO.IsolatedStorage on .NETCoreApp,Version=v1.0, but there is no run-time assembly compatible with win8-x64.
    One or more packages are incompatible with .NETCoreApp,Version=v1.0 (win8-x64).
```

Looks like **System.IO.IsolatedStorage** have no platform binaries:

https://github.com/dotnet/corefx/issues/10002

Because of this I can't run my application in **self-contained** mode and should care about framework installed on the host. So it would be good if you could get rid of **System.IO.IsolatedStorage** if possible.

Here is `project.json` of test application that I use:

```json
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0"
    },
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Exceptionless": "4.0.1890"  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimes": {
    "win10-x64": {},
    "win8-x64": {}
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  }
}
```

If you need - I can provide you with full application for investigation.

**Comment by niemyjski** [comment]
Is there any reason for declaring a runtimes section, which is what is causing this issue no (I read the linked github issue, but may need to reread it after my coffee)?? The goal of .net core is to run cross plat and by putting that section in there you are running only on windows?

**Comment by niemyjski** [comment]
What happens if you remove that section?

**Comment by otakusid** [comment]
if I remove that section I can't build application in the following way:

```
dotnet build --configuration release --runtime win8-x64
```

this allow me to receive **self-contained** application that can be launched on the host without installed framework. in this case I lose flexibility and should build separate version for each platform when I plan to host my application, but in the other hand I don't depend from the host configuration

**Comment by otakusid** [comment]
in other words I sacrifice flexibility of platforms that I can use for my application but win because of host configuration routine is simplified a lot

**Comment by niemyjski** [comment]
@ejsmith We'll have to do some thinking on this, I'd hate to remove functionality that exists and works just because you can't compile in one scenario (but we feel strongly it should work in all scenarios). I just don't get why you'd even get this error on windows, that's a supported runtime of isolated storage (indirectly).

**Comment by otakusid** [comment]
If I understand it right - I get errors because **System.IO.IsolatedStorage** have no precompiled assemblies. So when I try to produce self-contained package for my app, with all assemblies that required to run - I catch error because CLI could not find precompiled assembly for **System.IO.IsolatedStorage** for specified platform

**Comment by niemyjski** [comment]
@otakusid, We're going to leave this as is for now unless others run into this same issues. The work around is very simple, just reference the .netstandard 1.3 package for the time being (remove 1.5 reference and add reference to 1.3 for the exceptionless dependency). If you need any help, please let me know.

**Comment by dotnetshadow** [comment]
@niemyjski Hi there with regards to you last comment how do you do this?

> We're going to leave this as is for now unless others run into this same issues. The work around is very simple, just reference the .netstandard 1.3 package for the time being (remove 1.5 reference and add reference to 1.3 for the exceptionless dependency). If you need any help, please let me know.

**Comment by ErlendSB** [comment]
I'm also experiencing this. I'm building a netcoreapp1.0 for the debian.8-x64 runtime. 
Can you please explain the workaround? 
Does it involve building the package myself, or changing project.json in my solution?

**Comment by ejsmith** [comment]
Are you guys trying to tell it to use offline storage (isolated storage) or is this happening just because these assemblies are referenced in the client.

I think this should be a supported scenario. I'm not sure why it's failing. It seems like some sort of bug with .net core. I like the idea of the core Exceptionless client being as lightweight as possible, but it means it will break existing users if we move the offline storage into separate packages.

**Comment by niemyjski** [comment]
Just happens because they are referenced because it's picking the highest net standard and installing those dependencies.. So they implicitly reference windows only assemblies and that's why they are seeing this I think. Weird that it all works on my mac but it seems like some issues on Xamarin.

**Comment by ejsmith** [comment]
Yeah, those assemblies should work on the win8-x64 platform, but maybe it's something specific to Xamarin.  We need to spend the time to verify the client is working on Xamarin and take whatever steps are necessary to make it work.

If that means removing isolated storage and other things out of the core client package, then I think we need to do that.

**Comment by niemyjski** [comment]
I'll add this to my up-next task, which will be either later today or tomorrow.

**Comment by niemyjski** [comment]
@ErlendSB @dotnetshadow Any chance you could join our slack channel: http://slack.exceptionless.com and we can talk about this more in real time?

**Comment by niemyjski** [comment]
Almost think instead of pulling it out for now, we just remove it from the .net core build (https://github.com/dotnet/corefx/issues/9842) It's coming back in 2.x and will support xplat

**Comment by niemyjski** [comment]
So apparently even though isolated storage is available on Windows in general, they only support a single windows runtime....

**Comment by niemyjski** [comment]
We have a prerelease build that has some major improvements for xplat include isolated storage is currently removed until .net core 2.0 is released and we removed dependencies that were not xplat friendly (global mutexes). Can you please try this branch and let me know how it works for you.

 I'm closing, please comment on your experiences with the prerelease builds.

**Comment by hmvs** [comment]
Guys do you have any dates when nuget package without isolatedstorage will be out from 'prerelease' state?

**Comment by niemyjski** [comment]
I'm sorry, we got side tracked and didn't finish this up. I'll spend some time to look into the branch and try and get that merged in today or tomorrow and get a release out.

**Comment by niemyjski** [comment]
Just to follow up have you been using the prerelease package? Have you ran into any issues?

**Comment by hmvs** [comment]
We haven't. But we have tried to go into live with release one but encountered this problem.

**Comment by hmvs** [comment]
One more thing. We are using Serilog.Sinks.ExceptionLess. So could you please update it? Without it we can't publish our project as standalone app.

**Comment by niemyjski** [comment]
It should be on the current version. I'll update it here shortly. Going to do testing this morning and roll it out

**Comment by hmvs** [comment]
Thank you. Hoping to go live with it on Monday.

**Comment by niemyjski** [comment]
I've shipped it and will also update the serilog sink (https://github.com/exceptionless/Exceptionless.Net/releases/tag/v4.0.2)

**Comment by hmvs** [comment]
Thank you a lot.
