### ISSUE TITLE
Confusing ExceptionlessClient.CreateException() API

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#112]
Hi,

Most developers who type these lines of code expect a NullReferenceException thrown :
```csharp
ExceptionlessClient elClient = null;
elClient.CreateException(new Exception()).Submit();
```

But no exception is thrown because the CreateException() extension method only use the ExceptionlessClient reference as an argument for another method which can be null.

I think this behavior is confusing and I lost some time to understand why my events were not sent as expected.

**Comment by niemyjski** [comment]
This is the default behavior of extension methods (ability to call it on a null value). If the value is null we fall back to the default exceptionless client instance. 

Do you think we should make a breaking change and throw an argument null exception here? cc @ejsmith?

**Comment by CyberSinh** [comment]
Yes, I am personally in favor.

**Comment by niemyjski** [comment]
This will be fixed in a nightly pre release on nuget and we will merge it into stable in a few days.
