### ISSUE TITLE
Register ExceptionlessClient in a WPF app can create zombie process in memory

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#113]
Hi,
Register ExceptionlessClient in a WPF application seems to create zombie process if an exception is thrown early in the MainWindow constructor. So, you have to kill the process in the task manager.

If I don't register the ExceptionClient, the application crashes gracely and is correctly removed from the memory.

You will find attached a sample repro. Hope this helps.

[ExceptionlessZombieProcess.zip](https://github.com/exceptionless/Exceptionless.Net/files/404760/ExceptionlessZombieProcess.zip)

**Comment by niemyjski** [comment]
This has been fixed in a prelease client on nuget, can you please give it a try and let me know how it works out for you. We will be pushing this out to stable once https://github.com/exceptionless/Exceptionless.Net/pull/114 is merged in.

**Comment by CyberSinh** [comment]
Good job Blake. Thanks! Hope #114 will be merged soon.

**Comment by niemyjski** [comment]
Can you please try the nightly builds and let me know how they go. I don't want to merge these changes until they get some additional testing in.

**Comment by CyberSinh** [comment]
Everything seems to be fine on my machine with Exceptionless.Wpf 4.0.1895-pre.

**Comment by niemyjski** [comment]
I'm going to push this today I think :)
