### ISSUE TITLE
Topshelf Service Exception not sent to Exceptionless UI

### ISSUE THREAD

**Issue by ericbrunner** [exceptionless/Exceptionless.Net#115]
Hey Blake,

I utilze Topshelf and Serilog in addition to Exceptionless. When I run the attached code from the commandline all works well and the raised exception gets reported in the Exceptionless UI. If I install it as Windows Service the raised exception gets only reported in the Serilog RollFile at C:\logs. I tested a lot but can't find a setup issue on my side that causes that strange behaviour. I attached the last logs when the Service was running and the UI Screenshot.

Run from Commandline: 

RCS.Framework.Logger.ConsoleUI.Serilog.exe run  **[WORKS]**

Install as a Service:

RCS.Framework.Logger.ConsoleUI.Serilog.exe install

and then start , causes that logs and unreported exception.

thanks,
Eric
[RCS.Framework.Logger.zip](https://github.com/exceptionless/Exceptionless.Net/files/416375/RCS.Framework.Logger.zip)
[Logs_RCSFrameworkLoggerConsoleUISerilog.zip](https://github.com/exceptionless/Exceptionless.Net/files/416377/Logs_RCSFrameworkLoggerConsoleUISerilog.zip)

![exceptionlessui_noexceptionreported](https://cloud.githubusercontent.com/assets/6480047/17641025/7cd3f098-610f-11e6-9b81-ce7b139cbfb6.jpg)

**Comment by ericbrunner** [comment]
After putting 
ExceptionlessClient.Default.ProcessQueue() before Environment.Exit(-1) it finally works in Service mode, too. But if possible that fix should be added to the Serilog.Sinks.Exceptionless

**Comment by ericbrunner** [comment]
Topshelf itself registers a AppDomain.CurrentDomain.UnhandledException event handler and swallows all unhandled exceptions. My own handler didn't get called. So this is one root cause of the problem why exception don't get propagated to the Exceptionless Server on a windows service crash.

**Comment by niemyjski** [comment]
So when an unhandled exception isn't called you are not getting any exceptions logged because they exit before our unhandled exception handler is called? That kinda stinks.

**Comment by niemyjski** [comment]
The client will automatically call process queue in the unhandled application exception event handler as well as on process exit. I think they need to preserve the events from being called and let it crash. But that's their call.

**Comment by niemyjski** [comment]
@ericbrunner so I guess the solution is to log any exception in topshelf onexception and call process queue? Will that method only be called for unhandled exceptions?

**Comment by niemyjski** [comment]
@ejsmith ^^ You might be running into this with your topshelf services.

**Comment by ericbrunner** [comment]
I implemented my own solution to fix that Topshelf behaviour. But yes, all exception should go to the OnException Topshelf event. sstorie as developer should know more. My solution is to catch all exceptions in the Start and Stop method delegates of the Topshelf Host and submit it through serilog (log.error(ex,messagetemplate,data)) to exceptionless.

The Topshelf issue is that there UnhandledException handler hangs in an endless while (true) loop in case of an unhandled exception. Bad design.
