### ISSUE TITLE
Wrong stack information on exception

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#116]
Hi,

Is it normal that Exceptionless doesn't send the overriden StackTrace in this code?

```csharp
[Serializable]
public class WarningException : Exception
{
   private readonly string stackTrace = Environment.StackTrace; // define custom StackTrace
   public WarningException(string message) : base(message) { }
   public override string StackTrace => stackTrace;
}

var ex = new WarningException("fake");
Debug.WriteLine(ex.StackTrace);
client.SubmitException(ex); // the StackTrace is not sent by exceptionless

try
{
   throw new WarningException("fake2");
}
catch (WarningException ex2)
{
   client.SubmitException(ex2); // a StackTrace is sent but not the custom one
}

```

Thanks.

**Comment by CyberSinh** [comment]
Seems to be a .NET 4.x bug, more info at:
https://connect.microsoft.com/VisualStudio/feedback/details/758501/system-exception-stacktrace-and-tostring-provide-inconstent-stack-trace-data-when-stacktrace-property-is-redefined-in-derived-class

But perhaps Exceptionless could use a work around to get the overriden stack trace property before serializing exception...

**Comment by niemyjski** [comment]
@CyberSinh I don't see any work around for this. On a side note is there, any reason you'd want to do a custom stack trace? This seems like it could be a bad idea

**Comment by CyberSinh** [comment]
I used custom stack trace with "warning" exceptions which can be propagate by messaging system instead of throwing system.

A simple work around is:

```csharp

Messenger.Default.Send(new WarningException("Take care of...")); // exception sent doesn't have stack trace

try
{
   throw new WarningException("Take care of...");
}
catch (WarningException ex)
{
  Messenger.Default.Send(ex); // exception sent have stack trace
}
```

I need to inherent from the exception base class because all Exceptionless issue events must be exceptions.

**Comment by niemyjski** [comment]
You could just submit a warning log event that something happened, it doesn't need to be an exception. Sending a message around with the whole exception is heavy. What is your end goal? To see where a warning occurred?

**Comment by CyberSinh** [comment]
In fact, my bug tracker issue only take into account error event type (with stack trace, etc.). Log event type is only used for telemetry (usage features, etc.). That's why I would want to wrap all issues as exception for exceptionless.

**Comment by niemyjski** [comment]
Is there any work around for using the stack trace, we are just calling StackTrace on the exception instance so it should pick up anything you have overridden.

**Comment by CyberSinh** [comment]
I doesn't seem the case on my machine. Have you tried with the sample code provided above?

**Comment by niemyjski** [comment]
I haven't, you said there was a work around but I don't see anything on the connect issue.

**Comment by CyberSinh** [comment]
No, I don't have any work around (except that throwing the exception).

**Comment by niemyjski** [comment]
I'm going to close this as there appears to be an issue with computing the stack frames outside of our control. I've added a skipped test for this issue and referenced this so we can revisit in the future.

Would you mind open an issue on the core clr github issue tracker and reference this. Appears that you cannot new up a new stack trace from Environment.StackTrace (returned via overridden exception.StackTrace property as there will be no frames).
![screen shot 2016-08-15 at 1 08 05 pm](https://cloud.githubusercontent.com/assets/1020579/17674212/32dcc8ca-62ea-11e6-9ee5-fe1c66a385d7.png)

**Comment by niemyjski** [comment]
In the mean time a work around would be to throw the error and catch it.
