### ISSUE TITLE
Exceptionless.Net cannot be built with Visual Studio 2015

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#117]
Hi, 

If I try to compile Exceptionless with Visual Studio 2015, I get the following error:
`C:\GitHub\Exceptionless.Net\src\Exceptionless\Exceptionless.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\cyber\Documents\GitHub\Exceptionless.Net\src\Exceptionless\Exceptionless.xproj`

What can I do to build Exceptionless?

Thanks.

**Comment by niemyjski** [comment]
I'll update the readme! You need to install the .NET Core Runtime as we use the new project system and the exceptionless project also targets the .net core runtime. Did this solve this issue?

https://www.microsoft.com/net/core

**Comment by CyberSinh** [comment]
Yes, it works now. Thanks!

But installing the ".NET Core SDK for Windows" is not sufficient, we need to install the "VS 2015 Tooling Preview 2"...
