### ISSUE TITLE
.NET 4.0 build target

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.Net#12]
Everything seems to use the Exceptionless.Portable package, which is a portable client package (as the name suggests). However, PCL is not supported on .NET 4.0 unless patched. Can you add another, non-portable, build target for .NET 4.0?

This seems related to https://github.com/exceptionless/Exceptionless.Net/issues/5

**Comment by niemyjski** [comment]
We hadn't planned on on creating a non pcl core package, but will if required. Are you running into this often? How do you deploy your app? if it's msi based you can add a launch condition that requires this [patch](http://www.microsoft.com/en-us/download/details.aspx?id=3556) to be set. I know this isn't the best answer but we want to make it just work. We should never blow up...  If we did end up compiling as a full library what should we call it?

**Comment by Phyxion** [comment]
Yes, we really need a non-PCL package as many users still use an unpatched .NET installation. Most installations go through inno setup but a major part is automatically updated and we cannot silently install the patch there. About the naming, it's not really 'Portable' anymore, but you can create another build target that targets just .NET 4.0 (Client Profile, preferably). For example, you can do so by adding another project (maybe also sln) and referencing the same files. You can code in one sln / project but if you add another file you would have to reference it in the other project as well. Maybe you can also add another property group in the same .csproj file, I know you can do this with .NET 4.0 and .NET 4.5 although I don't know if you can do this with PCL.

Getting the Portable to compile as .NET 4.0 Client Profile is very easy, it requires you to change the WebRequest.CreateHttp method (it does not exist in .NET 4.0) and change the using statements in two files (I do not recall which ones, it's about MemberTypes.Field). As references you need to add System, System.Net, System.Runtime.Serialization and System.Xml.

**Comment by niemyjski** [comment]
I'll bring this up to the team for discussion. 

One thing we do in our production app is you can tell the msi installer that it requires specific things like minimum operating system / kb to be installed before your app will install. You could also target .NET 4.5 in your app and then it would be guaranteed to work. If you are running into this issue, I can guarantee you are hitting other issues on unpatched .net 4.0 machines. Since 4.5 is a sxs install, it actually modifies the behavior of your deployed .NET 4.0 app which is another thing to consider too.

**Comment by Phyxion** [comment]
But .NET 4.5 doesn't run on Windows XP. We would love to ditch Windows XP but as many users still run it we just cannot. With nsis we already check if .net 4.0 is installed and we could (probably) do so with the patch as well. However, this still doesn't help for the many users that get the update automatically (without the installer). I can constantly compile it myself, but it would be a lot easier if you could just set up another project that targets 4.0 (client profile). With 4.5 (and up) this isn't required anymore so it's only for 4.0.

**Comment by niemyjski** [comment]
Thanks for the heads up. I'll see what we can do. In the mean time, I'd recommend updating your installer to check for that kb and prompt the user and/or just compile a local build. The 2.0 client seems really stable so you shouldn't need to update it much until we have a solution.

**Comment by Phyxion** [comment]
We still run Exceptionless 1.x, which has a proper 4.0 client. We'll wait for a build of this 'portable' one before we migrate to 2.x.

**Comment by niemyjski** [comment]
We just had another customer run into this issue. On a personal note... Do people not run windows updates?

**Comment by Phyxion** [comment]
No, many don't...

Blake Niemyjski wrote:
>
> We just had another customer run into this issue. On a personal
> note... Do people not run windows updates?

**Comment by Phyxion** [comment]
http://stackoverflow.com/questions/16756047/produce-a-net-4-0-library-from-a-pcl-project-where-code-is-identical

That seems a decent solution.

**Comment by Phyxion** [comment]
I've been testing a bit, it's also possible to add another project configurations. However, the projects won't load if you have the .NET 4.0 configuration selected (you first need to change back to the regular PCL project configuration), I think this is because Visual Studio does not reload the project 'on the fly' and doesn't recognize the changes. It might be solvable by installing the targeting pack for VS but I didn't want to install this as it's yet another addon pack. 

That said, the idea from stackoverflow works like a charm (exactly as described there). I added a BuildAll.proj to the project root. Call it like:
> msbuild BuildAll.proj /p:Platform="Any CPU"

This will automatically create a .NET 4.0 dll (+ PCL) and this also creates a separate build (in the Release40 folders) for the other dlls (Extras, Wpf, etc) using the .NET 4.0 dll. 

There were a couple of code changes required to get it to compile for .NET 4.0, but it's pretty much identical. I created a PR for this.

One other thing, I noticed there are several conditional directives like NET20/NET40. When you remove the PORTABLE40 and set it to NET40 it won't build anymore (many missing includes). I don't know if these other directives are still used somewhere or if PORTABLE40 should always be there?

**Comment by Phyxion** [comment]
You still need to change your NuGet script by the way.

**Comment by niemyjski** [comment]
Thanks for the heads up. We never call build on the solution level, just on each project file: https://github.com/exceptionless/Exceptionless.Net/blob/master/Libraries/Build.ps1

**Comment by niemyjski** [comment]
I think we are always defining portable right now so I wonder what we need to do for that...

**Comment by Phyxion** [comment]
That looked like it indeed :) It seems you can indeed alter the powershell script using the settings I've provided to compile everything. I'm pretty certain you can make it work now :+1:

**Comment by Phyxion** [comment]
Any updates on this (and the new versions for releases)?

**Comment by niemyjski** [comment]
We've been working on the JavaScript client and then will be focusing on the serializer pull request and this. If you could submit a completed pull request for this it would be greatly appreciated.

**Comment by niemyjski** [comment]
I'm going to add this to our roadmap. We will be working on this shortly.

**Comment by Phyxion** [comment]
I already made a pull request for the project, you still have to add this to your own powershell build script (I hardly use powershell). I hope you can do this shortly indeed, looking forward to adding this.

**Comment by niemyjski** [comment]
Yes, thank you for your pull request (we appreciate it). We'll be working on this as soon as we can. We are finishing up work on the JavaScript client and then just need to do a few rounds of testing on it and then we will be taking a look into a serialization pull request and this.

**Comment by Phyxion** [comment]
Still nothing on this yet I think?

**Comment by niemyjski** [comment]
Not yet, we've been hard at work on the JavaScript client and are finishing that up. We've also been looking into multitargeting for dnx and this.

**Comment by Phyxion** [comment]
Any idea when this will be done? It shouldn't take much work :)

**Comment by niemyjski** [comment]
We don't have a date set, we are working as hard as we can every day
and this is near the top of the list. We have a pull request that is a
head of this one. A pull request would go a long ways to making this
get done much quicker.

On 5/20/15, Phyxion <notifications@github.com> wrote:
> Any idea when this will be done? It shouldn't take much work :)
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/exceptionless/Exceptionless.Net/issues/12#issuecomment-103900080


-- 
Thanks
-Blake Niemyjski

**Comment by niemyjski** [comment]
Could you please help us do some testing of this change by testing the following packages by pulling the nightly build (3.0.1343 or newer) package from our nightly NuGet feed: https://www.myget.org/F/exceptionless/api/v2

We just need to verify that if you are using pcl then the pcl package is used.. otherwise it's referenced from the NET40/45 packages folder. Lastly it works and doesn't blow up :).

**Comment by Phyxion** [comment]
I can't say that your myget feed is doing anything, all it prints is one line "DefaultPackagesScreenshots".

**Comment by niemyjski** [comment]
Please try this: https://www.myget.org/gallery/exceptionless

**Comment by Phyxion** [comment]
Going to test it tomorrow (early).

**Comment by Phyxion** [comment]
Added the myget as a NuGet source and it set up everything corectly (I verified in VS and if the files are indeed .NET 4.0).

**Comment by niemyjski** [comment]
Awesome! I need to do some pcl testing as well.

**Comment by niemyjski** [comment]
We are in the process of pushing [v3.1.0](https://github.com/exceptionless/Exceptionless.Net/releases/tag/v3.1.0) out to NuGet!
