### ISSUE TITLE
Error on referencing Exceptionless NuGet package to Xamarin projects

### ISSUE THREAD

**Issue by arvicxyz** [exceptionless/Exceptionless.Net#121]
I have a problem on referencing the Exceptionless package. Has anyone ever tried referencing Exceptionless to a Xamarin project? I am having errors when referencing it.

**Questions:**

1. What Exceptionless project type do I use? Is it Console and Service Applications?
2. What package do I reference? Exceptionless or Exceptionless.Portable?

**Error Message:**

``Could not install package 'System.Security.Principal.Windows 4.0.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.``

I have implemented several solutions and none worked for me right now. I tried referencing the package to a portable class library project and the same error occurs. Hope someone has tried this before and can help me with a solution. Thanks.

**Comment by niemyjski** [comment]
Hello,

1. You'd need to install the `Exceptionless` package (Console and Service Applications).
2. Just the latest `Exceptionless` package.

The new exceptionless package supports PCL, .NET Standard and .NET 4.5 frameworks. I believe that the there is an update to xamarin that adds support for .NET Standard. 

What version of Xamarin are you using?  I'm wondering if possibly you need to manually reference a lower .net standard (we support .net standard 1.2-1.5 and as the .net standard version gets bigger we turn on more things.. I'm thinking that maybe isolated storage in 1.4 may be causing this issue). Can you try updating to the latest xamarin studio/runtime and reinstalling.

If you can tell me the xamarin versions / runtimes you are using. I can also try locally on my mac.

**Comment by arvicxyz** [comment]
Hello,

I am currently using Xamarin version 6.0.2 (build 73).

Do I directly add the Exceptionless package to the *Xamarin.iOS* and *Xamarin.Android* project or do I have to other steps just for me to be able add these packages from NuGet?

Thanks.

**Comment by niemyjski** [comment]
I'm on version 6.1.0 but the way I installed it to was the portable project they generate and I changed the profile to:
<img width="483" alt="screen shot 2016-09-08 at 11 04 38 am" src="https://cloud.githubusercontent.com/assets/1020579/18356857/362f9cf0-75b4-11e6-894c-70699ebda074.png">

Then I was able to reference exceptionless. I know they added support for .net standard but I've yet to get that to work in any of my samples. Can you please try this and let me know.

**Comment by arvicxyz** [comment]
Wow! That solved my problem. Thank you.

So setting the Current Profile to PCL 4.6 - Profile 151 solves the issue.

Many thanks mate.

**Comment by niemyjski** [comment]
We've added .net standard support. I'm wondering if this story has gotten any better. Please let us know how it's working out.
