### ISSUE TITLE
Is logging thread safe?>

### ISSUE THREAD

**Issue by InlineAsm** [exceptionless/Exceptionless.Net#125]
Hi guys,

I have a question about exceptionless in general. Is the logging and reporting of exceptions thread safe or should I ensure myself that exceptionless is called by one thread at a time?

I ask this because I noticed the .net dictionary locking up because exceptionless is adding a key on one thread and reading from the dictionary in another.

![image](https://cloud.githubusercontent.com/assets/6095763/19017108/47d8965e-882f-11e6-9f71-778352358a67.png)

Keep up the good work on this project!

Ivar

**Comment by ejsmith** [comment]
It's definitely meant to be thread safe. If it's not then we need to fix it. Can you submit a failing test and or a fix for the issue you are seeing?

**Comment by InlineAsm** [comment]
If using the ConcurrentDictionary from .net is an option for you I would be happy to fix your ObservableaDictionary with it. If so I will submit a pull request tomorrow. It's quite late now where I live.

**Comment by ejsmith** [comment]
At one point we couldn't use it because it wasn't on all the platforms that we supported. Not sure where that stands now.

**Comment by InlineAsm** [comment]
I tested with the ConcurrentDictionary and indeed it makes the .Net Portable build fail. The ConcurrentDictionary did not make any tests fail. 

There are some libraries on the net that provide lock-less dictionaries or backport the concurrent dictionary to .Net Portable. But I don't think I should be the one that chooses one of another.

This is a deeper issue which I don't think I can solve for you. If you want I can create a test that shows the ObservableDictionary is the problem but it's widely known that the .Net Dictionary isn't thread-safe and I would only prove the obvious.

Let me know if you need more from me.

**Comment by ejsmith** [comment]
Thank you for looking into this. It may be easier for us to just add our own lock in the code.

**Comment by niemyjski** [comment]
@InlineAsm I just committed a fix for this which will be deployed to nuget as a prerelease package. Can you please try it out and let me know how it works for you.

@ejsmith need you to review this change as well.

**Comment by InlineAsm** [comment]
I was just sitting down to fix it for you. You beat me to it! The deadlock occurs only once in a while but I will let you know if I encounter any problems with it. I will also take a look at the commit to see if I find problems.

Thanks for your efforts.
