### ISSUE TITLE
Can't install package for MVC application targeting .NET 4.0

### ISSUE THREAD

**Issue by crowbarsolutions** [exceptionless/Exceptionless.Net#126]
Trying to install the NuGet Exceptionless.Mvc and Exceptionless packages into an existing MVC 4 application targeting .NET 4.0. I get the following message:

> Could not install package 'Exceptionless 4.0.1906'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

> Could not install package 'Exceptionless.Mvc 4.0.1906'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Unfortunately updating the application to .NET 4.5 isn't an option at the moment. Is there an older version that is still compatible?

**Comment by niemyjski** [comment]
Yes, you can install the v3.5 package for .NET 4.0 environments (https://www.nuget.org/packages/Exceptionless.Mvc/3.5.1738). Please let us know if you have any questions.
