### ISSUE TITLE
How to configure serverUrl when using log4net appender

### ISSUE THREAD

**Issue by NotMyself** [exceptionless/Exceptionless.Net#128]
I am trying to get exceptionless to capture log4net logging. I have a local instance of exceptionless running and I am using the following configuration.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="exceptionless" type="Exceptionless.ExceptionlessSection, Exceptionless.Extras"/>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler,log4net"/>
  </configSections>

  <exceptionless apiKey="BF97UD5k1z2Z63DaNQmpLGfbucIVwKwt7MwOmKEA" serverUrl="http://localhost:50000" />

  <log4net>
    <appender name="exceptionless" type="Exceptionless.Log4net.ExceptionlessAppender,Exceptionless.Log4net">
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%-4timestamp [%thread] %-5level %logger %ndc - %message%newline"/>
      </layout>
    </appender>

    <appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
      <param name="Threshold" value="DEBUG" />
      <layout type="log4net.Layout.PatternLayout">
        <param name="ConversionPattern" value="%d [%t] %-5p %c [%x] - %m%n" />
      </layout>
    </appender>
    <root>
      <level value="DEBUG"/>
      <appender-ref ref="exceptionless"/>
      <appender-ref ref="ConsoleAppender" />
    </root>
  </log4net>

  <startup>
      <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1"/>
  </startup>
</configuration>
```

I can see log messages going to the console, but nothing is sent to the server. What am I missing?

**Comment by NotMyself** [comment]
Modifying the Appender definition like so, got it working:

```xml
<appender name="Exceptionless" type="Exceptionless.Log4net.ExceptionlessAppender,Exceptionless.Log4net">
      <apiKey value="PxeO7gzfEnnK7yWPR8eURsbgqwIG5BEs7PyEITeB" />
      <serverUrl value="http://localhost:50000" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%-4timestamp [%thread] %-5level %logger %ndc - %message%newline"/>
      </layout>
    </appender>
```

**Comment by NotMyself** [comment]
[Here](https://github.com/NotMyself/CalculatorService/blob/exceptionless) is an example application showing the problem. If you comment out lines [12-13 in the app.config](https://github.com/NotMyself/CalculatorService/blob/exceptionless/src/CalculatorService/App.config#L12=L13), no logs get sent to exceptionless via the serverUrl defined in the default configuration.

**Note:** to get the console app to run you may need to run `scripts\register_uri.ps1` and give it your username to unblock the port. You can also start exceptionless using `scripts\start_exceptionless.ps1`.

**Comment by niemyjski** [comment]
It says https://github.com/NotMyself/CalculatorService/blob/exceptionless no longer exists.

**Comment by niemyjski** [comment]
Can you attach a small sample here?

**Comment by ejsmith** [comment]
https://github.com/NotMyself/CalculatorService/

**Comment by niemyjski** [comment]
I pulled down the exceptionless branch and it's not using log4net. Looking at your config section, it appears your on an older version of the client. But I think the real issue here is you are only using log4net adaptor (from what I can tell).  We won't know how to read the configuration unless you call client.StartUp() from your entry point (in the latest client). Or when you specify an api key in the appender. This is why you are not seeing anything until you specify the api key in the appender.

`By default, the appender will use the settings from the Exceptionless config section, but
you can also set it on the appender like this:` Perhaps that should also mention that the config section will only be read after calling StartUp(), we just assume that you are using another client integration that hooks up to error handlers as well. Thoughts?

**Comment by ejsmith** [comment]
He shouldn't need to configure anything. It uses the default client instance if you don't configure it. It should just work because his Exceptionless client is configured properly.

**Comment by ejsmith** [comment]
Or are you saying that the Exceptionless client isn't reading the config out because he didn't call startup?

**Comment by niemyjski** [comment]
Since he only has the log4net appender, there is nothing that triggers us to read a config section.

**Comment by ejsmith** [comment]
Ahh yeah. So just needs to call startup method, right?

**Comment by niemyjski** [comment]
Yep, just calling startup would work. It looks like he is on an older version of ExceptionlessClient so he'd need to call Register()

**Comment by ejsmith** [comment]
Do we have something in trouble shooting saying to make sure you call startup?

**Comment by niemyjski** [comment]
I don't think so, it's assumed it's done by the client integration

**Comment by NotMyself** [comment]
Thanks for looking into this @niemyjski & @ejsmith. From what I am reading here, the reason this does not work the way I expected it to is because I was relying on the log4net registration to bootstrap the exceptionless client. That makes sense, seems like the log4net appender should handle that.

@niemyjski you mentioned that I am using an older ExceptionlessClient. I think this was driven by the log4net appener nuget package. When working on this, I created the branch and switched to log4net (what my current day job project uses) then pulled the Exceptionless.log4net package. I assumed that it would pull the appropriate package. Maybe it needs to be updated.

Also, sorry for the stream of consciousness issue log here. I was simply updating it as I was troubleshooting. Came off a bit ramble-y I am sure. 😄

**Comment by niemyjski** [comment]
The log4net package is up-to-date as it's apart from the regular solution that gets built with all the other releases.

No, it's all good :). I'm not sure it's the appenders responsibility to call Register/Startup? Thoughts on this.. We don't know if you have any other integrations and we never touch the default instance, only fall back to it if you don't specify an api key in the appender.

**Comment by niemyjski** [comment]
I'll double check this, but it all installed everything fine this morning into that solution.

**Comment by niemyjski** [comment]
The latest version of log4net was installed

**Comment by marshafan** [comment]
Is there something in documentation tells about how to configure exceptionless as a log4net appender?I am using it this way in a project which is created by another resigned college ,and i came into a problem when rps is up to 150 ,the code "_logger.logInformation" is actually starving threads,so i have to comment it out for tempory solution.And i am trying to find out  the reason.

**Comment by niemyjski** [comment]
@marshafan yes, it's detailed in the readme: https://github.com/exceptionless/Exceptionless.Net/tree/main/src/Platforms/Exceptionless.Log4net for the Exceptionless.Log4net nuget package. I'd also look at this: https://exceptionless.com/docs/clients/dotnet/configuration/
