### ISSUE TITLE
Add Serilog.SelfLog logging in case of exceptionless internal errors

### ISSUE THREAD

**Issue by hmvs** [exceptionless/Exceptionless.Net#133]
As we have Serilog exceptionless sink we should follow Serilog rules. 
So if we have exception in exceptionless sink we should write to SelfLog, to be able to diagnose the problem in exceptionless. 

https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics
https://improveandrepeat.com/2014/09/debugging-serilog/

**Comment by niemyjski** [comment]
Thanks for logging this, is there any chance you'd be willing to submit a pr for this>

**Comment by hmvs** [comment]
I can try, later this or next week. 
Could you please throw some examples? You have told me that you have some logging for nlog.

**Comment by niemyjski** [comment]
Just need to implement an `IExceptionlessLog` logger like this: https://github.com/exceptionless/Exceptionless.Net/blob/f0494c8015fe8ba76cdb11b9b017c6c1d68f8749/src/Platforms/Exceptionless.NLog/NLogExceptionlessLog.cs

And then you'd just new up a new instance and pass it into the following method: https://github.com/exceptionless/Exceptionless.Net/blob/b43858182f8912fc2de87b3681919049e121af14/src/Exceptionless/Extensions/ExceptionlessConfigurationExtensions.cs#L195

**Comment by hmvs** [comment]
Can be closed
