### ISSUE TITLE
Nuget won't add Exceptionless v4 to Universal Windows app projects

### ISSUE THREAD

**Issue by billhenn** [exceptionless/Exceptionless.Net#134]
If you make a new UWP app project and try to add Exceptionless v4 to it with Nuget, the add fails, meaning UWP apps can't use Exceptionless.  It seems to have to do with some .NET standard issue.

**Comment by niemyjski** [comment]
so automapper fixed it by doing this https://github.com/AutoMapper/AutoMapper/commit/f3e345d958bb999a54c53e73660b51bf6e8c69ee which we are already doing. nuget is being stupid and not even looking at our .netstandard 1.2 package but our highest version.

 I think the short term work around is to manually reference the .netStandard 1.2 assemblies in our nuget package

**Comment by BillHenning** [comment]
FYI, I tested this again just now with the latest VS 2017 RC3 update and same problem.

**Comment by niemyjski** [comment]
I think we need to make some changes to our package

**Comment by niemyjski** [comment]
Looks like there are still issues with VS2017 RTM

**Comment by BillHenning** [comment]
Get trolling @Niemyjski!

**Comment by niemyjski** [comment]
@BillHenning can you please try the nightly builds to see if this any better with net standard 2.0 support

**Comment by BillHenning** [comment]
Still no workie... but I think it's because .NET Standard 2.0 isn't supported on UWP yet until Fall Creator's Update:
https://blogs.msdn.microsoft.com/dotnet/2017/08/25/uwp-net-standard-2-0-preview/

Remind me in a few weeks once that is out and I can look.

**Comment by kiran-bobade** [comment]
Any progress on this? encountering the same issue while installing **Exceptionless.AspNetCore** 4.3.2012 package into .NET Standard 2.0 assembly.  This package is restored using. NET Framework 4.6.1 instead of .NET standard 2.0.

**Comment by niemyjski** [comment]
You won't be able to bring the AspNetCore package in because it requires NetCoreApp as the target framework but you would be able to bring in the Exceptionless package, have you tried this?

**Comment by kiran-bobade** [comment]
Actually, we have all our startup code required to run AspNetCore app is in NetStandarad assembly. That means a Startup.cs class is in NetStandard assembly. 
If I install Exceptionless package I won't get the beauty of  `builder.UseExceptionless()` and we won't be having Web.config file to setup exceptionless configuration. All our framework code is targeting AspNetCore applications only.  

Do you have other recommendation?

**Comment by niemyjski** [comment]
You don't need a web.config file to configure Exceptionless in asp.net core. We had to take a dependency on netcoreapp instead of net standard 2.0 because it's the only way we can hook into diagnostics :\. You could fork the library and see what we could do to support just .net standard 2.0 or perhaps we put some of the code behind a compiler directive and target multiple frameworks.

**Comment by niemyjski** [comment]
@billhenn Can you please confirm if this is still an issue. I'm working on resolving / fixing all backlog items.

**Comment by niemyjski** [comment]
You should be able to upgrade to latest non signed package
