### ISSUE TITLE
Exceptionless client not being fired from a Unit Test

### ISSUE THREAD

**Issue by tBStar** [exceptionless/Exceptionless.Net#140]
Hi,

Using the self-hosted solution, I spent considerable amount of time trying to figure out why exceptions are not being logged from my unit tests. I have tried the following configurations but none of them worked:
- ExceptionlessClient.Default.Startup("kVCawYxPJXHSYz744sRsJHSDUron4zmB0ycPobEC");
- ExceptionlessClient.Default.Configuration.ReadFromConfigSection();
- [assembly: Exceptionless("kVCawYxPJXHSYz744sRsJHSDUron4zmB0ycPobEC", ServerUrl ="http://localhost:50000")]

Currently I have this:
public void Setup()
{
    ExceptionlessClient.Default.Startup("kVCawYxPJXHSYz744sRsJHSDUron4zmB0ycPobEC");
}

And in my test method, I have the following:
try
{
     throw new Exception();
}
catch (Exception ex)
 {
    ex.ToExceptionless()
    .AddTags(this.GetType().Name, System.Reflection.MethodBase.GetCurrentMethod().Name)
    .MarkAsCritical()
     .Submit();
}

It seems odd exceptions are being sent on the web form app but not in the unit test. Why am I not able to send exceptions to my self-hosted environment?

Fahd

**Comment by tBStar** [comment]
Man, you really should put out a statement in the wiki about writing events within unit tests because the fact that, events are not sent in real time for performance purposes, threw me off. When I called ExceptionlessClient.Default.ProcessQueue() at the end of my test method and it worked. Gee!

**Comment by niemyjski** [comment]
We talk about this a bit here: https://github.com/exceptionless/Exceptionless.Net/wiki/Troubleshooting#ensure-the-queue-has-time-to-process If you have any tips on the verbiage on this please let me know.

**Comment by tBStar** [comment]
I am talking front and center on the homepage! just kidding. I think it's ok where it belongs, I overlooked the troubleshooting section.
-Fahd
