### ISSUE TITLE
Verify email in self-hosting

### ISSUE THREAD

**Issue by tBStar** [exceptionless/Exceptionless.Net#141]
Hi,

I using the self-hosted solution. After I received the verification email and click the link, I get a 404 error, the link url is : http://localhost:50000/account/verify?token=XUpNHidzpfA1Ct5DT9EIzbEcHySmHoSDa6yzf0G1
What am I doing wrong?

**Comment by niemyjski** [comment]
Are you using clean urls as per the self hosting documentation? What is your base_url application setting set to in the web.config?

**Comment by tBStar** [comment]
It was the missing # !!, now I am able to invite users but still getting the email not verified thing.

**Comment by niemyjski** [comment]
@tBStar is there any chance we can meet up and I can take a look into this with you?

**Comment by niemyjski** [comment]
We've released 4.0.1 which should really help with these issues. Can you try upgrading and see if this helps.

**Comment by niemyjski** [comment]
@tBStar did upgrading to 4.0.1 resolve this issue? Can you please let me know if it didn't help by commenting on this issue and we'll reopen it.
