### ISSUE TITLE
Enable client logging through app.json

### ISSUE THREAD

**Issue by MihaMarkic** [exceptionless/Exceptionless.Net#143]
Hi guys,

Seems like there is no support for enabling client logging in asp.net core app through app.json.
I can add it...

**Comment by niemyjski** [comment]
Yes, if you could, that would be greatly appreciate! If we could align the flow like our existing logging attributes that would be awesome.

**Comment by niemyjski** [comment]
We do have a branch for the new stuff (/csproj) which is a WIP there are blocking `dotnet pack` issues that need to get worked out)

**Comment by niemyjski** [comment]
@MihaMarkic master has all the latest csproj changes as well as asp.net core changes

**Comment by niemyjski** [comment]
Is there any chance you'd be willing to send in a pr for this?

**Comment by niemyjski** [comment]
@MihaMarkic would you mind submitting a pr for this? In the mean time I'm going to close this to keep the issues clean.
