### ISSUE TITLE
Deprecate unsigned packages and make all packages signed

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#149]
This is what the .net team and others are doing, we should do this and cleanup our code base greatly :)

**Comment by niemyjski** [comment]
Part of this cleanup should involve: https://github.com/exceptionless/Exceptionless.Net/commit/cba3bb12f01a88b32c756409ee8152f8feee9bc6

**Comment by moogle001** [comment]
Any chance of this any time soon? Or making an Exceptionless.Extensions.Logging.Signed?

**Comment by niemyjski** [comment]
It would be really nice to get this done and bump the major with only signed packages. Any chance you can submit a pr for just the logging signed
