### ISSUE TITLE
Handling of AggregateExceptions data of some inner exceptions is lost

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.Net#15]
The current `ErrorModel` allows for just one inner exception, whereas the `AggregateException` allows for multiple inner exceptions. Right now it appears that the aggregate exception is logged; the first inner exception is logged, but the rest of the inner exceptions gets lost.

Also when `AggregateExceptions` is nested within another `AggregateException` information is lost, because of a missing `.Flatten()` call.

**Comment by niemyjski** [comment]
Thanks for the sample, it appears that we need to special case AggregateExceptions even more. I'm not sure what the best thing to do would be when you have multiple inner exceptions. I can think of a few things.

1. You ignore aggregate exceptions and just submit the inners. This has a few flaws as you miss the root exception type (aggregate exception), and you also break ToExceptionless() as what do you return...
2. We update the EventBuilder's Target property to contain multiple events and all of the methods just duplicate the actions on every event. Or For backwards compatibility we add a Targets property and we leave the Target property and have it return the first Targets item.

@ejsmith any thoughts?

**Comment by niemyjski** [comment]
@srijken could you do a new pull request or do you want me to double revert :)?

**Comment by ejsmith** [comment]
Need to look into this some more, but I am worried about what would break if we changed inner to support multiple errors. Need to dig in to find out.
