### ISSUE TITLE
Can't "Using Exceptionless" namespace!

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless.Net#150]
Steps:
1. Open vs2017.
2. create a asp.net core 1.0 mvc project.
3. PM>Install-Package Exceptionless.AspNetCore
4.  local the Startup.cs class and try to "Using Exceptionless;"

results:
1. no "Exceptionless" pop up. just like the dll never be installed!

Info:
1.PM's logs as below:
PM> Install-Package Exceptionless.AspNetCore
正在还原 c:\users\a08-03\documents\visual studio 2017\Projects\WebApplication4\WebApplication4\WebApplication4.csproj 的包...
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Exceptionless.AspNetCore'
  GET https://www.myget.org/F/imagesharp/FindPackagesById()?id='Exceptionless.AspNetCore'
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Exceptionless.AspNetCore' 261 毫秒
  GET https://www.nuget.org/api/v2/package/Exceptionless.AspNetCore/4.0.1951
  OK https://www.nuget.org/api/v2/package/Exceptionless.AspNetCore/4.0.1951 678 毫秒
  OK https://www.myget.org/F/imagesharp/FindPackagesById()?id='Exceptionless.AspNetCore' 1086 毫秒
正在安装 Exceptionless.AspNetCore 4.0.1951。
正在安装 NuGet 程序包 Exceptionless.AspNetCore 4.0.1951。
正在提交还原...
Writing lock file to disk. Path: c:\users\a08-03\documents\visual studio 2017\Projects\WebApplication4\WebApplication4\obj\project.assets.json
c:\users\a08-03\documents\visual studio 2017\Projects\WebApplication4\WebApplication4\WebApplication4.csproj 的还原在 2.89 sec 内完成。
已从 WebApplication4 成功卸载“Microsoft.AspNetCore.Hosting.Abstractions 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.AspNetCore.Http 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.AspNetCore.Http.Abstractions 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.AspNetCore.Http.Extensions 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.AspNetCore.Http.Features 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.AspNetCore.WebUtilities 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.Extensions.Configuration.Abstractions 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.Extensions.DependencyInjection.Abstractions 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.Extensions.DiagnosticAdapter 1.0.0”
已从 WebApplication4 成功卸载“Microsoft.Extensions.FileProviders.Abstractions 1.0.1”
已从 WebApplication4 成功卸载“Microsoft.Extensions.Logging.Abstractions 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.Extensions.ObjectPool 1.0.1”
已从 WebApplication4 成功卸载“Microsoft.Extensions.Options 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.Extensions.PlatformAbstractions 1.0.0”
已从 WebApplication4 成功卸载“Microsoft.Extensions.Primitives 1.0.1”
已从 WebApplication4 成功卸载“Microsoft.Net.Http.Headers 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.NETCore.Platforms 1.0.2”
已从 WebApplication4 成功卸载“Microsoft.NETCore.Targets 1.0.1”
已从 WebApplication4 成功卸载“Microsoft.Win32.Primitives 4.0.1”
已从 WebApplication4 成功卸载“Microsoft.Win32.Registry 4.0.0”
已从 WebApplication4 成功卸载“NETStandard.Library 1.6.0”
已从 WebApplication4 成功卸载“runtime.native.System 4.0.0”
已从 WebApplication4 成功卸载“runtime.native.System.IO.Compression 4.1.0”
已从 WebApplication4 成功卸载“runtime.native.System.Net.Http 4.0.1”
已从 WebApplication4 成功卸载“System.AppContext 4.1.0”
已从 WebApplication4 成功卸载“System.Buffers 4.0.0”
已从 WebApplication4 成功卸载“System.Collections 4.0.11”
已从 WebApplication4 成功卸载“System.Collections.Concurrent 4.0.12”
已从 WebApplication4 成功卸载“System.Collections.Immutable 1.2.0”
已从 WebApplication4 成功卸载“System.Collections.NonGeneric 4.0.1”
已从 WebApplication4 成功卸载“System.Collections.Specialized 4.0.1”
已从 WebApplication4 成功卸载“System.ComponentModel 4.0.1”
已从 WebApplication4 成功卸载“System.ComponentModel.Primitives 4.1.0”
已从 WebApplication4 成功卸载“System.ComponentModel.TypeConverter 4.1.0”
已从 WebApplication4 成功卸载“System.Console 4.0.0”
已从 WebApplication4 成功卸载“System.Diagnostics.Contracts 4.0.1”
已从 WebApplication4 成功卸载“System.Diagnostics.Debug 4.0.11”
已从 WebApplication4 成功卸载“System.Diagnostics.DiagnosticSource 4.0.0”
已从 WebApplication4 成功卸载“System.Diagnostics.Process 4.1.0”
已从 WebApplication4 成功卸载“System.Diagnostics.StackTrace 4.0.1”
已从 WebApplication4 成功卸载“System.Diagnostics.Tools 4.0.1”
已从 WebApplication4 成功卸载“System.Diagnostics.Tracing 4.1.0”
已从 WebApplication4 成功卸载“System.Dynamic.Runtime 4.0.11”
已从 WebApplication4 成功卸载“System.Globalization 4.0.11”
已从 WebApplication4 成功卸载“System.Globalization.Calendars 4.0.1”
已从 WebApplication4 成功卸载“System.Globalization.Extensions 4.0.1”
已从 WebApplication4 成功卸载“System.IO 4.1.0”
已从 WebApplication4 成功卸载“System.IO.Compression 4.1.0”
已从 WebApplication4 成功卸载“System.IO.Compression.ZipFile 4.0.1”
已从 WebApplication4 成功卸载“System.IO.FileSystem 4.0.1”
已从 WebApplication4 成功卸载“System.IO.FileSystem.Primitives 4.0.1”
已从 WebApplication4 成功卸载“System.Linq 4.1.0”
已从 WebApplication4 成功卸载“System.Linq.Expressions 4.1.1”
已从 WebApplication4 成功卸载“System.Net.Http 4.1.1”
已从 WebApplication4 成功卸载“System.Net.NameResolution 4.0.0”
已从 WebApplication4 成功卸载“System.Net.Primitives 4.0.11”
已从 WebApplication4 成功卸载“System.Net.Sockets 4.1.0”
已从 WebApplication4 成功卸载“System.Net.WebSockets 4.0.0”
已从 WebApplication4 成功卸载“System.ObjectModel 4.0.12”
已从 WebApplication4 成功卸载“System.Reflection 4.1.0”
已从 WebApplication4 成功卸载“System.Reflection.Emit 4.0.1”
已从 WebApplication4 成功卸载“System.Reflection.Emit.ILGeneration 4.0.1”
已从 WebApplication4 成功卸载“System.Reflection.Emit.Lightweight 4.0.1”
已从 WebApplication4 成功卸载“System.Reflection.Extensions 4.0.1”
已从 WebApplication4 成功卸载“System.Reflection.Metadata 1.3.0”
已从 WebApplication4 成功卸载“System.Reflection.Primitives 4.0.1”
已从 WebApplication4 成功卸载“System.Reflection.TypeExtensions 4.1.0”
已从 WebApplication4 成功卸载“System.Resources.ResourceManager 4.0.1”
已从 WebApplication4 成功卸载“System.Runtime 4.1.0”
已从 WebApplication4 成功卸载“System.Runtime.Extensions 4.1.0”
已从 WebApplication4 成功卸载“System.Runtime.Handles 4.0.1”
已从 WebApplication4 成功卸载“System.Runtime.InteropServices 4.1.0”
已从 WebApplication4 成功卸载“System.Runtime.InteropServices.RuntimeInformation 4.0.0”
已从 WebApplication4 成功卸载“System.Runtime.Numerics 4.0.1”
已从 WebApplication4 成功卸载“System.Runtime.Serialization.Primitives 4.1.1”
已从 WebApplication4 成功卸载“System.Security.Claims 4.0.1”
已从 WebApplication4 成功卸载“System.Security.Cryptography.Algorithms 4.2.0”
已从 WebApplication4 成功卸载“System.Security.Cryptography.Cng 4.2.0”
已从 WebApplication4 成功卸载“System.Security.Cryptography.Csp 4.0.0”
已从 WebApplication4 成功卸载“System.Security.Cryptography.Encoding 4.0.0”
已从 WebApplication4 成功卸载“System.Security.Cryptography.OpenSsl 4.0.0”
已从 WebApplication4 成功卸载“System.Security.Cryptography.Primitives 4.0.0”
已从 WebApplication4 成功卸载“System.Security.Cryptography.X509Certificates 4.1.0”
已从 WebApplication4 成功卸载“System.Security.Principal 4.0.1”
已从 WebApplication4 成功卸载“System.Security.Principal.Windows 4.0.0”
已从 WebApplication4 成功卸载“System.Text.Encoding 4.0.11”
已从 WebApplication4 成功卸载“System.Text.Encoding.Extensions 4.0.11”
已从 WebApplication4 成功卸载“System.Text.Encodings.Web 4.0.0”
已从 WebApplication4 成功卸载“System.Text.RegularExpressions 4.1.0”
已从 WebApplication4 成功卸载“System.Threading 4.0.11”
已从 WebApplication4 成功卸载“System.Threading.Tasks 4.0.11”
已从 WebApplication4 成功卸载“System.Threading.Tasks.Extensions 4.0.0”
已从 WebApplication4 成功卸载“System.Threading.Thread 4.0.0”
已从 WebApplication4 成功卸载“System.Threading.ThreadPool 4.0.10”
已从 WebApplication4 成功卸载“System.Threading.Timer 4.0.1”
已从 WebApplication4 成功卸载“System.Xml.ReaderWriter 4.0.11”
已从 WebApplication4 成功卸载“System.Xml.XDocument 4.0.11”
已从 WebApplication4 成功卸载“System.Xml.XmlDocument 4.0.1”
已将“Exceptionless 4.0.1951”成功安装到 WebApplication4
已将“Exceptionless.AspNetCore 4.0.1951”成功安装到 WebApplication4
已将“Microsoft.AspNetCore.Hosting.Abstractions 1.1.1”成功安装到 WebApplication4
已将“Microsoft.AspNetCore.Hosting.Server.Abstractions 1.1.1”成功安装到 WebApplication4
已将“Microsoft.AspNetCore.Http 1.1.1”成功安装到 WebApplication4
已将“Microsoft.AspNetCore.Http.Abstractions 1.1.1”成功安装到 WebApplication4
已将“Microsoft.AspNetCore.Http.Extensions 1.1.1”成功安装到 WebApplication4
已将“Microsoft.AspNetCore.Http.Features 1.1.1”成功安装到 WebApplication4
已将“Microsoft.AspNetCore.WebUtilities 1.1.1”成功安装到 WebApplication4
已将“Microsoft.Extensions.Configuration.Abstractions 1.1.1”成功安装到 WebApplication4
已将“Microsoft.Extensions.DependencyInjection.Abstractions 1.1.0”成功安装到 WebApplication4
已将“Microsoft.Extensions.DiagnosticAdapter 1.1.0”成功安装到 WebApplication4
已将“Microsoft.Extensions.FileProviders.Abstractions 1.1.0”成功安装到 WebApplication4
已将“Microsoft.Extensions.Logging.Abstractions 1.1.1”成功安装到 WebApplication4
已将“Microsoft.Extensions.ObjectPool 1.1.0”成功安装到 WebApplication4
已将“Microsoft.Extensions.Options 1.1.1”成功安装到 WebApplication4
已将“Microsoft.Extensions.PlatformAbstractions 1.1.0”成功安装到 WebApplication4
已将“Microsoft.Extensions.Primitives 1.1.0”成功安装到 WebApplication4
已将“Microsoft.Net.Http.Headers 1.1.1”成功安装到 WebApplication4
已将“Microsoft.NETCore.Platforms 1.1.0”成功安装到 WebApplication4
已将“Microsoft.NETCore.Targets 1.1.0”成功安装到 WebApplication4
已将“Microsoft.Win32.Primitives 4.3.0”成功安装到 WebApplication4
已将“Microsoft.Win32.Registry 4.3.0”成功安装到 WebApplication4
已将“NETStandard.Library 1.6.1”成功安装到 WebApplication4
已将“runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.native.System 4.3.0”成功安装到 WebApplication4
已将“runtime.native.System.IO.Compression 4.3.0”成功安装到 WebApplication4
已将“runtime.native.System.Net.Http 4.3.0”成功安装到 WebApplication4
已将“runtime.native.System.Security.Cryptography.Apple 4.3.0”成功安装到 WebApplication4
已将“runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple 4.3.0”成功安装到 WebApplication4
已将“runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“System.AppContext 4.3.0”成功安装到 WebApplication4
已将“System.AppDomain 2.0.11”成功安装到 WebApplication4
已将“System.Buffers 4.3.0”成功安装到 WebApplication4
已将“System.Collections 4.3.0”成功安装到 WebApplication4
已将“System.Collections.Concurrent 4.3.0”成功安装到 WebApplication4
已将“System.Collections.Immutable 1.3.0”成功安装到 WebApplication4
已将“System.Collections.NonGeneric 4.3.0”成功安装到 WebApplication4
已将“System.Collections.Specialized 4.3.0”成功安装到 WebApplication4
已将“System.ComponentModel 4.3.0”成功安装到 WebApplication4
已将“System.ComponentModel.Primitives 4.3.0”成功安装到 WebApplication4
已将“System.ComponentModel.TypeConverter 4.3.0”成功安装到 WebApplication4
已将“System.Console 4.3.0”成功安装到 WebApplication4
已将“System.Data.Common 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.Contracts 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.Debug 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.DiagnosticSource 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.Process 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.StackTrace 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.Tools 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.TraceSource 4.3.0”成功安装到 WebApplication4
已将“System.Diagnostics.Tracing 4.3.0”成功安装到 WebApplication4
已将“System.Dynamic.Runtime 4.3.0”成功安装到 WebApplication4
已将“System.Globalization 4.3.0”成功安装到 WebApplication4
已将“System.Globalization.Calendars 4.3.0”成功安装到 WebApplication4
已将“System.Globalization.Extensions 4.3.0”成功安装到 WebApplication4
已将“System.IO 4.3.0”成功安装到 WebApplication4
已将“System.IO.Compression 4.3.0”成功安装到 WebApplication4
已将“System.IO.Compression.ZipFile 4.3.0”成功安装到 WebApplication4
已将“System.IO.FileSystem 4.3.0”成功安装到 WebApplication4
已将“System.IO.FileSystem.Primitives 4.3.0”成功安装到 WebApplication4
已将“System.Linq 4.3.0”成功安装到 WebApplication4
已将“System.Linq.Expressions 4.3.0”成功安装到 WebApplication4
已将“System.Net.Http 4.3.1”成功安装到 WebApplication4
已将“System.Net.NameResolution 4.3.0”成功安装到 WebApplication4
已将“System.Net.Primitives 4.3.0”成功安装到 WebApplication4
已将“System.Net.Sockets 4.3.0”成功安装到 WebApplication4
已将“System.Net.WebSockets 4.3.0”成功安装到 WebApplication4
已将“System.ObjectModel 4.3.0”成功安装到 WebApplication4
已将“System.Reflection 4.3.0”成功安装到 WebApplication4
已将“System.Reflection.Emit 4.3.0”成功安装到 WebApplication4
已将“System.Reflection.Emit.ILGeneration 4.3.0”成功安装到 WebApplication4
已将“System.Reflection.Emit.Lightweight 4.3.0”成功安装到 WebApplication4
已将“System.Reflection.Extensions 4.3.0”成功安装到 WebApplication4
已将“System.Reflection.Metadata 1.4.1”成功安装到 WebApplication4
已将“System.Reflection.Primitives 4.3.0”成功安装到 WebApplication4
已将“System.Reflection.TypeExtensions 4.3.0”成功安装到 WebApplication4
已将“System.Resources.ResourceManager 4.3.0”成功安装到 WebApplication4
已将“System.Runtime 4.3.0”成功安装到 WebApplication4
已将“System.Runtime.CompilerServices.Unsafe 4.3.0”成功安装到 WebApplication4
已将“System.Runtime.Extensions 4.3.0”成功安装到 WebApplication4
已将“System.Runtime.Handles 4.3.0”成功安装到 WebApplication4
已将“System.Runtime.InteropServices 4.3.0”成功安装到 WebApplication4
已将“System.Runtime.InteropServices.RuntimeInformation 4.3.0”成功安装到 WebApplication4
已将“System.Runtime.Numerics 4.3.0”成功安装到 WebApplication4
已将“System.Runtime.Serialization.Primitives 4.3.0”成功安装到 WebApplication4
已将“System.Security.Claims 4.3.0”成功安装到 WebApplication4
已将“System.Security.Cryptography.Algorithms 4.3.0”成功安装到 WebApplication4
已将“System.Security.Cryptography.Cng 4.3.0”成功安装到 WebApplication4
已将“System.Security.Cryptography.Csp 4.3.0”成功安装到 WebApplication4
已将“System.Security.Cryptography.Encoding 4.3.0”成功安装到 WebApplication4
已将“System.Security.Cryptography.OpenSsl 4.3.0”成功安装到 WebApplication4
已将“System.Security.Cryptography.Primitives 4.3.0”成功安装到 WebApplication4
已将“System.Security.Cryptography.X509Certificates 4.3.0”成功安装到 WebApplication4
已将“System.Security.Principal 4.3.0”成功安装到 WebApplication4
已将“System.Security.Principal.Windows 4.3.0”成功安装到 WebApplication4
已将“System.Text.Encoding 4.3.0”成功安装到 WebApplication4
已将“System.Text.Encoding.Extensions 4.3.0”成功安装到 WebApplication4
已将“System.Text.Encodings.Web 4.3.0”成功安装到 WebApplication4
已将“System.Text.RegularExpressions 4.3.0”成功安装到 WebApplication4
已将“System.Threading 4.3.0”成功安装到 WebApplication4
已将“System.Threading.Tasks 4.3.0”成功安装到 WebApplication4
已将“System.Threading.Tasks.Extensions 4.3.0”成功安装到 WebApplication4
已将“System.Threading.Thread 4.3.0”成功安装到 WebApplication4
已将“System.Threading.ThreadPool 4.3.0”成功安装到 WebApplication4
已将“System.Threading.Timer 4.3.0”成功安装到 WebApplication4
已将“System.Xml.ReaderWriter 4.3.0”成功安装到 WebApplication4
已将“System.Xml.XDocument 4.3.0”成功安装到 WebApplication4
已将“System.Xml.XmlDocument 4.3.0”成功安装到 WebApplication4
已将“System.Xml.XmlSerializer 4.3.0”成功安装到 WebApplication4
执行 nuget 操作花费时间 2.07 sec
已用时间: 00:00:06.8620797

what's wrong with that?

**Comment by ZhiqiangTao** [comment]
investigation:
the vs2015 is ok!!!........

**Comment by niemyjski** [comment]
Did you find the culprit? What was the issue?
