### ISSUE TITLE
Can not "using Exceptionless"?

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless.Net#151]
1.I use vs2017 to create a aspnet core mvc project(target framework4.6.1+asp.net core 1.0 template)
2.I search the "Exceptionless.AspNetCore" with the version of '4.0.1933' in the nuget, and add it to my project.
3.In the startup.cs, I want to add "using Exceptionless" namespace, but I failed. no intellisense pop up, just like no exceptionless.dll added.

Strangely!!!
I use vs2017 to create a aspnet core mvc project(target framework4.6.1+asp.net core **1.1** template),
repeat the steps 2 and 3, it works fine!

so, what's wrong with it? I also use the vs2015 to create a asp.net core 1.0 project and add exceptionless's dll from nuget, it also works fine!!!

how do I fix this issue?

**Comment by niemyjski** [comment]
I'll take a look

**Comment by niemyjski** [comment]
We recently updated to target 1.1, what's displayed in the nuget output window when you try installing the package?

**Comment by ZhiqiangTao** [comment]
below is output window's message:
正在还原 c:\users\a08-03\documents\visual studio 2017\Projects\exceptionlessDemos\WebApplication1\WebApplication1.csproj 的包...
正在安装 NuGet 程序包 Exceptionless.AspNetCore 4.0.1933。
正在提交还原...
Writing lock file to disk. Path: c:\users\a08-03\documents\visual studio 2017\Projects\exceptionlessDemos\WebApplication1\obj\project.assets.json
c:\users\a08-03\documents\visual studio 2017\Projects\exceptionlessDemos\WebApplication1\WebApplication1.csproj 的还原在 1.09 sec 内完成。
已从 WebApplication1 成功卸载“System.Diagnostics.StackTrace 4.0.1”
已将“Exceptionless 4.0.1933”成功安装到 WebApplication1
已将“Exceptionless.AspNetCore 4.0.1933”成功安装到 WebApplication1
已将“System.AppDomain 2.0.11”成功安装到 WebApplication1
已将“System.Data.Common 4.1.0”成功安装到 WebApplication1
已将“System.Diagnostics.StackTrace 4.0.2”成功安装到 WebApplication1
已将“System.Diagnostics.TraceSource 4.0.0”成功安装到 WebApplication1
已将“System.Xml.XmlSerializer 4.0.11”成功安装到 WebApplication1
执行 nuget 操作花费时间 2.41 sec
已用时间: 00:00:03.5436325
========== 已完成 ==========

正在还原 NuGet 程序包...
已用时间: 00:00:02.2876066
========== 已完成 ==========

**Comment by ZhiqiangTao** [comment]
ps: I'm from Chinese, the language package of the VS2017 is zh-cn. Maybe the bing translator is needed...

**Comment by ZhiqiangTao** [comment]
Now, I have updated all my projects from 1.0 to 1.1 to walk around this issue. But I just want to know the reason for this issue.

**Comment by niemyjski** [comment]
I'll take a look and let you know as soon as I have more info.

**Comment by niemyjski** [comment]
If you can create a new sample application that is broken and send it to me that would be greatly appreciated. I can then further look into this issue. Currently, I'm unable to reproduce. 
![screen shot 2017-04-17 at 9 52 04 am](https://cloud.githubusercontent.com/assets/1020579/25092553/c9f00bd0-2353-11e7-92bf-f87b5b208bcc.png)
I just followed your exact steps using 4.0.1933 as well as the newest package (which we recommend using and both worked).

**Comment by ZhiqiangTao** [comment]
@niemyjski I sent an email with the attachment to "'blake.niemyjski@exceptionless.mail.intercom.io'", you can take a look. ths.

**Comment by niemyjski** [comment]
Are you running the latest VS2017 update? I'm not sure what could be different but it works flawlessly on my two virtual machines.

See the video below (click to view)
[![Alt text](https://content.screencast.com/users/bniemyjski/folders/Camtasia/media/a1d55a12-8b01-45cb-b580-27237b4e039d/FirstFrame.jpg)](https://www.screencast.com/t/V79ucBrO)

**Comment by niemyjski** [comment]
Are you accepting the terms of the nuget packages in the dialog that pops up? As shown in my video? I'm wondering if that could be causing it?

**Comment by ZhiqiangTao** [comment]
I'm sorry to answer you so late. it's the same with your pops up.
I have update my project from core 1.0 to 1.1 and resolve this problem. Close this issue
