### ISSUE TITLE
Cann't see the exception in the All Events dashboard [Real-time]!

### ISSUE THREAD

**Issue by ZhiqiangTao** [exceptionless/Exceptionless.Net#153]
I met an issue as below:
1. I use the code "ex.ToExceptionless().Submit()" to add an exception.
2. then I refer to the All Events dashboard, but  nothing shows.
3. after much time, the exception I added before can show in the dashboard.
4. after that, I did the step 1 with different exception many times, but I can't see them anymore!

what's wrong with it? does the real-time problem?

I investigated that:
1.if I can see the exception in the All Events dashboard, the package I caught by the fiddler ""POST http://hostip:hostport/api/v2/events HTTP/1.1"" **must** be sent.
2. I see the request in the fiddler, it contains the summary of the exceptions I added before.
3. Maybe the above "api/v2/events" affects this issue.

**Comment by niemyjski** [comment]
Were you able to resolve what was occurring? My guess is if your account was throttled, you wouldn't see anything coming in and the client would turn itself off for about 5 minutes.

**Comment by ZhiqiangTao** [comment]
aha, this is my code fault, I create a  client instance with ctor, not use the XXX.Default.XXX(the best official ways).
I saw the source code as below:
#region Default
        private static readonly Lazy<ExceptionlessClient> _defaultClient = new Lazy<ExceptionlessClient>(() => new ExceptionlessClient());

        public static ExceptionlessClient Default {
            get { return _defaultClient.Value; }
        }
 #endregion

maybe the instances created by two ways are not the same. the instance created by ctor(when the application starts up) can work well, but then when I try to use the XXX.Default.XXX, it can not work.

Now, I only use the  XXX.Default.XXX, anything is be ok!
thanks a lot.
