### ISSUE TITLE
.netstand2.0 System.AppDomain collision

### ISSUE THREAD

**Issue by majian159** [exceptionless/Exceptionless.Net#158]
Error: CS0433
The type 'AppDomain' exists in both 'System.AppDomain, Version=2.0.11.0, Culture=neutral, PublicKeyToken=a741d64a8a4710e8' and 'System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by niemyjski** [comment]
We have a polyfill that needs to be removed for 2.0. Would you mind submitting a pr with a new framework target for 2.0 and remove the dependency (https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Exceptionless.csproj#L52)

**Comment by majian159** [comment]
This will bring other changes,I'm afraid to produce dirty code.
`            if (provider is ParameterInfo)
            {
                ParameterInfo p = (ParameterInfo)provider;
#if NETSTANDARD1_0 || NETSTANDARD1_1 || NETSTANDARD1_2 || NETSTANDARD1_3 || NETSTANDARD1_4 || NETSTANDARD1_5 && !NETSTANDARD2_0
                return ((attributeType != null) ? p.GetCustomAttributes(attributeType, inherit) : p.GetCustomAttributes(inherit)).ToArray();
#else
                return (attributeType != null) ? Attribute.GetCustomAttributes(p, attributeType, inherit) : Attribute.GetCustomAttributes(p, inherit);
#endif
            }`

**Comment by niemyjski** [comment]
Yeah, I'm thinking maybe it might be best to rethink all those net standard attributes in the near future. It's find to produce some dirty code (for now), unless you have any ideas on how to clean that up. Maybe we could do NETSTANDARD && !NETSTANDARD2_0 (so we could replace all the if's with NETSTANDARD for the ones where it's all ors and just negate the ones that are not supported?

**Comment by niemyjski** [comment]
Is the pr ready to be merged in? Is there anything I can do to help?

**Comment by niemyjski** [comment]
@majian159 have you run into any issues with our nightly nuget package?

**Comment by niemyjski** [comment]
I'm closing this as it's in master, just needs to be deployed.

**Comment by zlzforever** [comment]
Could you please build a new package and upload to nuget? This bug cause my project build failed. Thanks a lot.

**Comment by niemyjski** [comment]
@zlzforever sorry for the delay we've been testing and making changes a couple times a week. It's finishing up and we'll get a release out very soon, maybe even today. Could you try adding a package source for https://www.myget.org/gallery/exceptionless

**Comment by zlzforever** [comment]
Appreciate  👍

**Comment by niemyjski** [comment]
We've pushed out v4.1.0

**Comment by majian159** [comment]
This version solves the problem, thank you very much.
