### ISSUE TITLE
Missing '@version' information in data returned by Exceptionless

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#160]
The data returned by Exceptionless is sometimes inconsistent.
In most cases, I have the information of the version of my software in the data:

`data ": {" @version ":" 5.7.2.5 "}`

but more and more often this information is not not present.

Did I miss something? Is there anything I can do to make the return of my software version systematic?

Thank you.

**Comment by niemyjski** [comment]
We try and detect it automatically by the assembly's version attributes (https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Plugins/Default/080_VersionPlugin.cs). It's best to explicitly set it in your app if you know the version. Are you finding that if you set it, it's not round tripped? If you can give me an exact use case I can look into it and get it resolved.

**Comment by CyberSinh** [comment]
Hi Blake,

I will try to hard code the version information as:

`config.DefaultData[Event.KnownDataKeys.Version] = Assembly.GetExecutingAssembly().GetName().Version.ToString();`

I'll keep you informed.
Thanks.

**Comment by niemyjski** [comment]
There is a helper on config to set the version: https://github.com/exceptionless/Exceptionless.Net/blob/27129f34229937dea727c0332d848be9cd626e98/test/Exceptionless.Tests/Configuration/ConfigurationTests.cs#L40

**Comment by CyberSinh** [comment]
Yes, it's more elegant with this helper. Thanks!
