### ISSUE TITLE
Abstract serialization/deserialization of events and settings.

### ISSUE THREAD

**Issue by edwardmeng** [exceptionless/Exceptionless.Net#163]
In the high load environment, the json serialization/deserialization became the bottle neck of performance, There will be too many temporary files kept. Now there is more than 10G, and increased day by day.
So could you please make the serialize/deserialize abstraction, that we can replace the json.net with MessagePack  or ProtoBuf to fix this problem.

**Comment by niemyjski** [comment]
What kind of serialization issues are you seeing? Are you using in memory storage on the client? If you have this many log messages we recommend only using the in memory storage client. The serialization is abstracted but it's not separated for settings and submission, it's all the same client. If the client was to be changed, then the server side would also need to be updated to support a different protocol.

**Comment by edwardmeng** [comment]
We are using FolderObjectStorage on the client, and storing the generated files on the SSD partition. In this senario, we have did deep investigation that the serialization/deserialization consumes 80% time in the hole process. So we just wanna replace Json.Net with MessagePack or ProtoBuf in the writing files and reading files, but not submission which leads inconsistent protocol.
Now there is only IJsonSerializer interface used storage and submission, which is not suitable for binary serialization/deserialization, and cannot separate the storage process and submission process. So in this situation, we cannot extend based on this interface.
At the same time, we cannot use the in memory storage, since it's not safe for many production accidents. Only the file storage is safety for production environment. We can deployed with the fastest hard disk, but the performance bottle neck should be fixed at the same time.

**Comment by niemyjski** [comment]
It would be nice to split out the serializers / storage for settings and events, but I think it would be overkill to split out the serializers for settings storage, settings retrieval, event storage, and event submission. We've said early on, that there is a high cost to pay for using folder / disk storage of events and for high throughput scenarios we do not recommend it as you are taking an extra two serialization hits per event. With that said I agree more could be done, by probably changing the on disk serializer. I think we are open to accepting a change for this. For now, I think you could replace the default queue implementation (copy the existing source) and change how events are serialized and deserialized to disk. I think this would be the easiest and fastest way and you could let us know what works the best.

@ejsmith do you have any thoughts on this?

**Comment by edwardmeng** [comment]
In our production, we have inherited and customized the FolderObjectStorage implementation to serialize/deserialize events with MessagePack as following:
```cs
internal class MessagePackFolderObjectStorage: FolderObjectStorage, IObjectStorage
    {
        private readonly IDependencyResolver _resolver;

        public MessagePackFolderObjectStorage(IDependencyResolver resolver, string folder) : base(resolver, folder)
        {
            _resolver = resolver;
            MessagePackSerializer.SetDefaultResolver(new ExceptionlessFormatterResolver());
        }

        T IObjectStorage.GetObject<T>(string path)
        {
            if (IsNullOrWhiteSpace(path))
                throw new ArgumentNullException(nameof(path));

            try
            {
                using (var stream = File.OpenRead(Path.Combine(Folder, path)))
                {
                    return MessagePackSerializer.Deserialize<T>(stream);
                }
            }
            catch (Exception ex)
            {
                if (
#if !NetCore
                    ex is ThreadAbortException || ex is StackOverflowException || 
#endif
                    ex is OutOfMemoryException)
                    throw;
                _resolver.GetLog().Error($"Failed to deserialize '{typeof(T)}' from path '{path}': " + ex.Message, exception: ex);
                return null;
            }
        }

        bool IObjectStorage.SaveObject<T>(string path, T value)
        {
            if (IsNullOrWhiteSpace(path))
                throw new ArgumentNullException(nameof(path));
            var fullPath = Path.Combine(Folder, path);
            var directory = Path.GetDirectoryName(fullPath);
            if (!IsNullOrEmpty(directory) && !Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            try
            {
                using (var writer = File.OpenWrite(fullPath))
                {
                    MessagePackSerializer.Serialize(writer, value);
                }
            }
            catch (Exception ex)
            {
                if (
#if !NetCore
                    ex is ThreadAbortException || ex is StackOverflowException || 
#endif
                    ex is OutOfMemoryException)
                    throw;
                _resolver.GetLog().Error($"Failed to serialize '{typeof(T)}' to path '{path}': " + ex.Message, exception: ex);
                return false;
            }

            return true;
        }
    }
```
At the same time we did performance testing about it. The testing result is as following:
SSD Hard Disk, Total Throughput 583,740,634

Senario | Total Duration | CPU Usage | Average Throughput | Logging Duration | Performance Lost
------ | ------ | ------ | ------ | ------ | ------
Json.Net | 01:02:38 | 98% | 155285 | 00:17:04 | 27.25%
MessagePack | 00:48:49 | 62% | 199218 | 00:03:15 | 6.66%
No Log | 00:45:34 | 30% | N/A | N/A | N/A

Then you can see there will be an significant improvement after replace Json.Net with MessagePack, and it will not effect of the submission process.

**Comment by niemyjski** [comment]
Thanks for the benchmarks, Someday it might be nice to have a nuget package for message pack, how did you get logging duration?

**Comment by edwardmeng** [comment]
MessagePack Logging Duration = MessagePack Total Duration - No Log Total Duration
Json.Net Logging Duration = Json.Net Total Duration - No Log Total Duration

**Comment by niemyjski** [comment]
Would you be interested in adding a maker interface for serialization of events and updating the client for this. That would make it much easier to swap out the serializer for only the storage and loading of events!

**Comment by edwardmeng** [comment]
Should I request a pr according to your suggestion, since this will lead many change points. e.g. event post job, folder storage, extension methods.

**Comment by niemyjski** [comment]
My understanding was this would only affect client file storage. I know we have a single serializer interface and I was thinking about adding a marker interface that inherits from the one we have and that would only be used for loading and saving of events / settings from disk.

**Comment by edwardmeng** [comment]
I have requested pr according to your suggestion. Please refer to #166 . The interface IEventSerializer was created only for the client file storage(FolderObjectStorage & IsolatedStorageObjectStorage) to load and save events except settings. At the same time the DefaultJsonSerializer implemented the interface for the default registration in the dependency injection container.

**Comment by niemyjski** [comment]
Thanks for the PR!
