### ISSUE TITLE
Isn't this a bug, you're calling an asynchronous action but you are not synchronizing with it?

### ISSUE THREAD

**Issue by leidegre** [exceptionless/Exceptionless.Net#164]
https://github.com/exceptionless/Exceptionless.Net/blob/e46241a63af4f6bbbdb31c9aaa4b211dedee5139/src/Platforms/Exceptionless.WebApi/ExceptionlessHandleErrorAttribute.cs#L23

**Comment by niemyjski** [comment]
I think this could be a bug... Are you seeing any issues relating to this? I think this should be 
`WrappedFilter.ExecuteExceptionFilterAsync(actionExecutedContext, cancellationToken).ConfigureAwait(false).GetAwaiter().GetResult();` Is there any chance you could try making this change locally and let me know if you run into any issues. A PR would be greatly appreciated.

**Comment by leidegre** [comment]
I just stumbled across it as I was reviewing the code while thinking about how to best integrate exceptionless. I've decided to not use the pre-packaged exception filter for various reasons but I think the change you suggested is necessary. I don't have a test case that I can exercise right now.

**Comment by niemyjski** [comment]
I've fixed this in the nightly which can be downloaded from myget. I'll do some more testing on this but the sample app is working great with this change... If you run into any issues please let us know!
