### ISSUE TITLE
A little Bug，Send Email For verification .

### ISSUE THREAD

**Issue by MaxXue** [exceptionless/Exceptionless.Net#169]
## This's Url link's is for  verification email, buy it does't work. So I find it is lost lost "**!**".
http://192.168.1.125:8004/#/account/verify?token=/qRc0V4ybOji5RGMorEdoJyqqzLqOZhEBhulN1f4C
=============================
# http://192.168.1.125:8004/#!/account/verify?token=/qRc0V4ybOji5RGMorEdoJyqqzLqOZhEBhulN1f4C

================================
SO, please Fixed, thanks.
P.s. I honw my english so bad , sorry!

**Comment by niemyjski** [comment]
Was the ! listed in the base url of the web.config? I think I fixed this yesterday morning in my asp.net core branch but wanted to confirm. If this is not the case and let me know so I can reopen the issue and take a closer look.

**Comment by MaxXue** [comment]
I don't konw where it's happened? I just konw the web send verification email in my email box. I click the links , it's does't work. I find the link lost "!".
the web.config in my web site . It's ok. 
### add key="BaseURL" value="http://192.168.1.125:8004/#" 
I just change the Host And Port.
Maybe. the link  lost "!" Or email box remove the "!". sorry I don't konw . i want you konw and  help me to fixed.
By the way.
In the Web.config ,Email Client Settings. there are have 5 options. 
SmtpHost、SmtpPort、SmtpEncryption、SmtpUser、SmtpPassword。the WebsiteMode is Production. 
but It's does't work. 
the logs write "mail from address must be same as authorization user". I download the project and check it. In the "Exceptionless.Insulation" ,"MailKitMailSender.cs"，the Line 58, it need Settings.Current.SmtpFrom ,but in the web.config it does't have this option.maybe you forget this.

**Comment by niemyjski** [comment]
I've confirmed the #! issue has been resolved in the nightly builds, your fix in the web.config is the right fix.

If you add SmtpFrom to the config it will pick up the setting, we didn't include it there because I didn't think it made sense to be setting it. But perhaps we should add it to the default list. Did that resolve your issue with the email?

**Comment by MaxXue** [comment]
Yes.It's ok .thank you for you Reply。I hopes it's note waste your times.

**Comment by niemyjski** [comment]
Never feel like you are wasting our time, we want to hear for you and confirm it is or is not an issue and ensure you are being helped!
