### ISSUE TITLE
Exceptionless UI Not working with a virtual directory

### ISSUE THREAD

**Issue by fduverger** [exceptionless/Exceptionless.Net#17]
When an IIS virtual directory is created  the UI stop showing logged exceptions.

**Comment by niemyjski** [comment]
I'll push this fix after the client builds

**Comment by fduverger** [comment]
Great! Thanks

**Comment by niemyjski** [comment]
The latest clients are being pushed and will be available shortly.

**Comment by fduverger** [comment]
Which clients need to be updated?

**Comment by niemyjski** [comment]
You would want to update all of the Exceptionless clients via the nuget package manager.

**Comment by fduverger** [comment]
Cool!

**Comment by niemyjski** [comment]
We are in the process of pushing [v3.1.0](https://github.com/exceptionless/Exceptionless.Net/releases/tag/v3.1.0) out to NuGet!
