### ISSUE TITLE
NLog Target should use Write(LogEventInfo logEvent)

### ISSUE THREAD

**Issue by snakefoot** [exceptionless/Exceptionless.Net#171]
https://github.com/exceptionless/Exceptionless.Net/blob/0925d4742e28325f17a31290a0fd68e323e93734/src/Platforms/Exceptionless.NLog/ExceptionlessTarget.cs#L36

Should override this method instead:

`protected override void Write(LogEventInfo logEvent)`

Then you don't have to worry about not handling the `AsyncLogEventInfo` correctly (which you don't)

**Comment by ejsmith** [comment]
Agreed. Can you submit a pull request for this change?

**Comment by snakefoot** [comment]
@ejsmith Just doing code-review. Not using ExceptionLess

**Comment by niemyjski** [comment]
Fixed in https://github.com/exceptionless/Exceptionless.Net/commit/585057e09a9d357c906a030eb8c906d29e12b384 Thanks for reporting these issues! It's greatly appreciated

**Comment by niemyjski** [comment]
@snakefoot We are very grateful for your help and time (https://github.com/exceptionless/Exceptionless.Net/releases/tag/v4.2.1).  Please feel free to join our slack or code review any of our projects (Exceptionless or [Foundatio](https://github.com/FoundatioFx/Foundatio)) :).
