### ISSUE TITLE
NLog Target skip allocation of List when no tags

### ISSUE THREAD

**Issue by snakefoot** [exceptionless/Exceptionless.Net#172]
https://github.com/exceptionless/Exceptionless.Net/blob/0925d4742e28325f17a31290a0fd68e323e93734/src/Platforms/Exceptionless.NLog/ExceptionlessClientExtensions.cs#L52

No need to allocate `List<string>`-object and inserting into properties-Dictionary, when just wanting to check if any Tags.

**Comment by ejsmith** [comment]
Agreed with this change as well.

**Comment by snakefoot** [comment]
@ejsmith Just doing code-review. Not using ExceptionLess

**Comment by snakefoot** [comment]
Maybe it could be fixed by extending the suggested solution in #173 (Check for propertyKey = "Tags")

**Comment by niemyjski** [comment]
Fixed in https://github.com/exceptionless/Exceptionless.Net/commit/585057e09a9d357c906a030eb8c906d29e12b384 Thanks for reporting these issues! It's greatly appreciated
