### ISSUE TITLE
NLog Target skip allocation of dictionary when no ContextData

### ISSUE THREAD

**Issue by snakefoot** [exceptionless/Exceptionless.Net#174]
https://github.com/exceptionless/Exceptionless.Net/blob/0925d4742e28325f17a31290a0fd68e323e93734/src/Platforms/Exceptionless.NLog/ExceptionlessClientExtensions.cs#L14

No need to allocate Dictionary-object and inserting into properties-Dictionary, when just wanting to check if any ContextData.

**Comment by niemyjski** [comment]
Fixed in https://github.com/exceptionless/Exceptionless.Net/commit/585057e09a9d357c906a030eb8c906d29e12b384 Thanks for reporting these issues! It's greatly appreciated
