### ISSUE TITLE
Use `Ben.Demystifier` to produce better stack traces

### ISSUE THREAD

**Issue by megakid** [exceptionless/Exceptionless.Net#177]
I've noticed when I send in a "demystified" stack trace it doesn't quite display as cleanly as I'd like in the exceptionless web UI.  Maybe Exceptionless.Net could use this library internally (if the exception isn't already demystified)

https://github.com/benaadams/Ben.Demystifier

**Comment by niemyjski** [comment]
We've thought about source embedding this and running it but haven't had the time to play around with it. It's going to make it into net standard 2.1 release which will be really nice. What kind of issue are you seeing? It doesn't appear to do all the inner exceptions only 1 deep.

**Comment by Jaans** [comment]
+1 for adding to Exceptionless.
With all the noise these days from stack traces, it sure would be nice to be able to have Exceptionless use this for .NET stack traces. (We're using it in .NET Framework 4.7)
