### ISSUE TITLE
When the submit fail, can it be output locally

### ISSUE THREAD

**Issue by Varorbc** [exceptionless/Exceptionless.Net#179]
ex.ToExceptionless().Submit(); //if submit fail
can it be output locally

**Comment by Varorbc** [comment]
No failure to submit, just one of my assumptions.can you tell how to use nlog  to output locally by register internal loggers

**Comment by niemyjski** [comment]
You can register up the nlog logger by running: `ExceptionlessClient.Default.UseLogger(new Exceptionless.NLog.NLogExceptionlessLog())` which will new up https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Platforms/Exceptionless.NLog/NLogExceptionlessLog.cs and output the internal client logs to NLog.

Please let us know if you need any help or you run into an issue with submit.

**Comment by Varorbc** [comment]
My NLog.Config
```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="Logs/internal-nlog.txt">

  <extensions>
    <add assembly="Exceptionless.NLog"/>
  </extensions>
  
  <targets async="true">
    <target xsi:type="Exceptionless" name="exceptionless" apiKey="Key">
      <field name="host" layout="${machinename}" />
      <field name="identity" layout="${identity}" />
      <field name="windows-identity" layout="${windows-identity:userName=True:domain=False}" />
      <field name="process" layout="${processname}" />   
    </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="exceptionless" />
  </rules>
</nlog>
```
Use NLog

`ExceptionlessClient.Default.Configuration.UseLogger(new NLogExceptionlessLog());`

But when I use the wrong serverUrl, I found that the local did not output log

**Comment by niemyjski** [comment]
I world recommend not setting the api key in the nlog.config and just remove the attribute. Thet will create an internal instance for logging. The last line where you call uselogger is not needed as it is only for internal logging of our client. I hope this helps

**Comment by Varorbc** [comment]
I am for reference [NLog.config](https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Platforms/Exceptionless.NLog/readme.txt#L33),why you tell me not setting the api key in the nlog.config now.
Can you give me a demo(when I use the wrong serverUrl, exceptionless can local output log
)?Thank you very much

**Comment by niemyjski** [comment]
We recommend setting the api key in the app/web.config by setting it in the nlog.config it creates a separate isolated client to submit the logs and you have a lot less control over configuration. I'd recommend taking a look at the samples folder in this repository, we have almost every scenario covered and if something isn't working please let us know. You should only set the serverUrl if you are self hosting.

**Comment by niemyjski** [comment]
It’s all good, I’ll check out our samples and update the nlog integration as needed. How are you setting the storage path?

**Comment by niemyjski** [comment]
Thanks for the update, How is everything working out now that it's configured?

**Comment by Varorbc** [comment]
Yes, but do you know why it sends me so frequently?

**Comment by niemyjski** [comment]
I'm not sure what you mean by that. Can you please expand on frequently?
