### ISSUE TITLE
Configuration Changes event

### ISSUE THREAD

**Issue by bbrcomputers** [exceptionless/Exceptionless.Net#18]
Hi,

I am 'upgrading' our existing exceptionless implementation from v1 to v2 and came across this line of code :

client.ConfigurationUpdated += (sender, args) => UpdateConfiguration();

It no longer exists and I don't see this documented on the upgrade page. Is this an oversight (or am I just plain blind) ?

(Email received from Blake reads)

I currently don't see any event for this in the new system. I think we need to add something back to: https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Shared/Configuration/SettingsManager.cs to fire when it's been updated. Could you please log this here: https://github.com/exceptionless/Exceptionless.Net/issues/new 

 	 	 	 	 
Blake Niemyjski from Exceptionless	8 May 2015	 
 	 	 	 	 
Regards,

Alex Caudron

**Comment by niemyjski** [comment]
Hello,

Did wiring up to the `client.Configuration.Settings.Changed += OnSettingsChanged;` fix this issue?

**Comment by bbrcomputers** [comment]
Hi Blake,

Syntax wise it did work, however I never got it to test.  There are too
many problems trying to convert from v1 to v2.  I think it has mainly to do
with the fact that v1 was error driven while v2 is event driven.

We are going to try to do a complete rewrite by approaching our goal in an
event driven thinking.

Regards,

Alex

**Comment by bbrcomputers** [comment]
Hi Blake,

I am trying to host a local exceptionless environment so I can start
changing our app (which I will also run local) to write errors  to my local
DB.  This will enable me to do everything away from our other environments
(which my colleagues are using)

So, I followed the steps on the hosting website as best as I could (never
used any of these tools before), and installed the required tools under
this folder :
C:\Development\Exceptionless\Libraries as seperate folders underneath :

     elasticsearch-1.5.0
     MongoDB
     Redis

I am baffled by step iv (4) : Update the connection strings in the
Web.config file to point to your Elasticsearch, MongoDBand Redis servers.

The web.config (as installed) is :
  <connectionStrings>
    <add name="MongoConnectionString"
connectionString="mongodb://localhost/exceptionless" />
    <add name="RedisConnectionString" connectionString="" />
    <add name="ElasticSearchConnectionString" connectionString="
http://localhost:9200" />

How do these relate to where I installed them and how would I change this
config ?
I do have the port numbers for MongoDB and Redis.
I did create a data\db folder for MongoDB.

I can run the Start-MongoDb.ps1 and Start-ElasticSearch.bat (as mentioned
in StartBackEndServers) and it looks as if I can get both servers to run.

Step 3 I also need to investigate (sorry I'm not a web developer) : Setup
IIS and add the Exceptionless API website
I have already downloaded the API website, but not sure how to set up IIS.
I have VS2013 installed, so I do know I have IIS8 Express

I am also seriously considering writing a beginners article on CodeProject
to explain in more detail how to get all this going for a local host,
because I have been grabbing pieces all over the internet to get this far,
and anybody who wants to give it a quick try (but doesn't know these
tools), will not get going easily.

Regards,

Alex

**Comment by niemyjski** [comment]
If you are just wanting to run this locally to test your dev project, you could just start the project and run it (after setting up mongo and elastic search) as the default connection strings will just work. If you are wanting to host this and not have to start visual studio to test you'll need to install iis as part of the windows features, then launch the IIS Manager app from the start menu, then configure the default site to point to the bin folder.

If you want to meet up, I could help you get everything up and running.

**Comment by bbrcomputers** [comment]
Hi Blake,

OK - I am battling to get the API web site to start in IIS, but if I don't
need it (I can use VS), I will try this route.

How do you want to meet up since I'm in Centurion (South Africa).  Can't
image you're close by.

I'll keep you posted on my progress.

Regards,

Alex.

**Comment by niemyjski** [comment]
If you want to join our chat room: https://gitter.im/exceptionless/Discuss and send me a message when you are on. I'll try and be around. We could join a remote meeting via teamviewer and take a look at this together.

**Comment by bbrcomputers** [comment]
Hi Blake,

I decided, just to get going, to use your webhosting (trial) in order to
see what I can do on my client side.  Mainly to try and figure out what to
do to 'intercept' and send errors to your portal.

I created a project called Test, and clicked on download and configure
client (giving the screen : Download & Configure Project "Test" Client)

on step 4 : Import the Exceptionless namespace and add a call to
ExceptionlessClient.Default.Register() during the startup of your app.
I get an error : Error 30 'Exceptionless.ExceptionlessClient' does not
contain a definition for 'Register' and no extension method 'Register'
accepting a first argument of type 'Exceptionless.ExceptionlessClient'
could be found (are you missing a using directive or an assembly reference?)


Any idea what my problem is ?

Regards,

Alex

**Comment by niemyjski** [comment]
@bbrcomputers  I'm really sorry I just saw your reply. If you want to jump on the chat room. I'd be more than happy to do a remote meeting and take a look into this. Were you able to get this working? Chances are you might be using the wrong package if that extension method isn't picked up.

**Comment by niemyjski** [comment]
@bbrcomputers I'm going to close this as I feel that this has been resolved. If you still need help, I'd be more than happy to do a remote meeting and take a look into this.
