### ISSUE TITLE
Setting User name on .NET Core Api 

### ISSUE THREAD

**Issue by pauljame** [exceptionless/Exceptionless.Net#181]
Hello,

I am trying to set the column "User" from Exceptionless. 
My Api have some unprotected/anonymous actions and some JWT token protected.

So, when my protected action are called I´d like to log in Exceptionless with the user name sended with token.
I tried like that inside my protected API action:
`ExceptionlessClient.Default.Configuration.SetUserIdentity(model.Email, model.Nome);`

that works fine, but than all subsequent anonymous action calls uses the same identity.

Is that the right way to do that? Why Exceptionless did not use the User.Identity.Name values ?

Thanks

**Comment by niemyjski** [comment]
The best way would be to call SetHttpContext when logging (https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Platforms/Exceptionless.AspNetCore/ExceptionlessExtensions.cs#L126) this will populate the user and request info.

```cs
ExceptionlessClient.Default.CreateLog(typeof(Program).FullName, "This is so easy", "Info").SetHttpContext(context).Submit();
```

Please let us know if you have any questions or need assistance, please see this for more information on submitting data.
https://github.com/exceptionless/Exceptionless.Net/wiki/Sending-Events#log-messages-feature-usages-404-and-custom-event-types
