### ISSUE TITLE
ArgumentNullException in DependencyResolverExtensions.Resolve

### ISSUE THREAD

**Issue by nmklotas** [exceptionless/Exceptionless.Net#184]
Hi,

We got some crashes from our users. We are using Exceptionless.Web 4.1.1972.0 with Win32 Service.

```System.ArgumentNullException: Value cannot be null.
Parameter name: resolver
at Exceptionless.Dependency.DependencyResolverExtensions.Resolve[TService](Exceptionless.Dependency.IDependencyResolver resolver, Exceptionless.Dependency.TService defaultImplementation) at offset 13
at Exceptionless.ExceptionlessConfigurationExtensions.UseTraceLogEntriesPlugin(Exceptionless.ExceptionlessConfiguration config, System.Nullable`1 defaultMaxEntriesToInclude) at offset 178
at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object state) at offset 7
```

**Comment by niemyjski** [comment]
From looking at this stack trace, the only way this exception would have happened is if that plugin registration failed and we failed to log the exception to the internal logger. For that to fail than configuration had to have been created with a null logger. Would you please show all of your client configuration settings you are using to configure your app with any api keys masked out.

**Comment by nmklotas** [comment]
I'm using Exceptionless only like this:

First in AssemblyInfo.cs i declare this:
```
[assembly: Exceptionless.Configuration.Exceptionless("xxxxxxxxxxxxxxxxxxx")]
```
Then I call EnableExceptionless in app startup (Program.cs):

```
private static void EnableExceptionless()
{
      ExceptionlessClient.Default.Startup();
      ExceptionlessClient.Default.UnregisterTaskSchedulerUnobservedTaskExceptionHandler();
 }
```
Nothing super fancy :)
I also don't use any app.config sections for Exceptionless.

**Comment by niemyjski** [comment]
Thanks, I'll do some more testing on this on full framework. I'll add some null checks to configuration so it should fail fast.

**Comment by niemyjski** [comment]
I've added some extra checks in the latest builds and ran this code through 1000 iterations and threw errors so the logger would be picked up and it was rock solid. I'm going to close this until we have a reproducible example or test. I'm really not sure what's going on here but I hope my new checks will help figure it out as I'm sure it's happening (from your stack trace).
