### ISSUE TITLE
Log messages being auto-truncated

### ISSUE THREAD

**Issue by jaygurnani** [exceptionless/Exceptionless.Net#191]
If the the message content gets too long with EventTargets in NLog, NLog allows you to split the log message into 2. (see here: https://github.com/NLog/NLog/issues/1014). Is it currently possible for the ExceptionlessTarget to do this as well? Currently if log messages are too long, it gets auto-truncated.

**Comment by niemyjski** [comment]
Hello,

You could do this today with a plugin (https://github.com/exceptionless/Exceptionless.Net/wiki/Adding-Plugins) we just don't support it out of the box. You could model it after this plugin (https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Plugins/Default/005_HandleAggregateExceptionsPlugin.cs) which splits aggregate exceptions into multiple events.

**Comment by jaygurnani** [comment]
Great, thanks for the help. I will try and implement this.

**Comment by niemyjski** [comment]
Were you able to get this working?
