### ISSUE TITLE
ASPNetCore package is not working without passing ExceptionlessClient object to ToExceptionless() method

### ISSUE THREAD

**Issue by kiran-bobade** [exceptionless/Exceptionless.Net#197]
As mentioned in the readme and short video, I have installed exceptionless locally and it's running as expected. Then I created an asp.net core web API project by installing asp.net core package of exceptionless. Here is the code in my startup file,

   ```
 public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseExceptionless(new ExceptionlessClient()
            {
                Configuration =
                {
                    ApiKey = "WYBH1MR14YFuEvwZnaiDNjEo4vLRBK2epUSsoDHS",
                    ServerUrl = "http://localhost:50000",
                    Enabled = true,
                }
            });
            app.UseMvc();
        }
```
test code in API controller

```
 public ActionResult<IEnumerable<string>> Get()
        {
            new Exception("Test exception").ToExceptionless().Submit();

            return new string[] { "value1", "value2" };
        }
```
The above code is not logging exception on the local exceptionless server. If I pass, an object of   ExceptionlessClient to ToExceptionless() method it is working as expected. But, if I am passing my client information during the startup, why I need to pass it while submitting the exception?

**Comment by kiran-bobade** [comment]
Exceptionless.ASPNetCore package works if I do like,

```
app.UseExceptionless();
ExceptionlessClient.Default.Configuration.ApiKey = "WYBH1MR14YFuEvwZnaiDNjEo4vLRBK2epUSsoDHS";
            ExceptionlessClient.Default.Configuration.Enabled = true;
            ExceptionlessClient.Default.Configuration.ServerUrl = "http://localhost:50000";
```
In this case I don't have to new object of ExceptionlessClient class into ToExceptionless() method.

**Comment by niemyjski** [comment]
Hello,

This is because by default when you do ToExceptionless(client = null) it's using the ExceptionlessClient.Default instance which isn't configured. When you pass in a new Exceptionless instance to the UseExceptionless() it uses the instance you pass to it for logging and doesn't change the Exceptionless.Default Instance. It's best to just configure the default instance (which passing the api key to UseExceptionless) will do. Does this make sense?

**Comment by niemyjski** [comment]
Yes, I would configure it like this:

```cs
ExceptionlessClient.Default.Configuration.ServerUrl = "http://localhost:50000";
app.UseExceptionless("KEY_HERE");
```

**Comment by niemyjski** [comment]
Please let us know if you have any questions.
