### ISSUE TITLE
EnvironmentInfoCollector in Exceptionless.Extras throws Exceptions on Mono

### ISSUE THREAD

**Issue by bitbeans** [exceptionless/Exceptionless.Net#20]
On my test maschine (Ubuntu 14.04) i first had to install: libmono-microsoft-visualbasic11.0-cil

otherwise:

>System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

after installing the related package i got:

> EnvironmentInfoCollector: Unable to get physical memory. Error message: The requested feature is not implemented. 
EnvironmentInfoCollector: Unable to get process id. Error message: GetCurrentProcessId 
EnvironmentInfoCollector: Unable to get process name. Error message: GetModuleHandle 
EnvironmentInfoCollector: Unable to get thread id. Error message: GetCurrentThreadId

The problem is, that in ```Microsoft.VisualBasic.Devices``` the needed methods are not implemented:

See: https://github.com/mono/mono-basic/blob/master/vbruntime/Microsoft.VisualBasic/Microsoft.VisualBasic.Devices/ComputerInfo.vb

The report still works, but you will see reported errors in your log file.

**Comment by niemyjski** [comment]
Thanks for your commit! I've made a few comments on the commit. Also, can you please make sure to sign our CLA: so we can accept the pull request ( https://www.clahub.com/agreements/exceptionless/Exceptionless )

**Comment by niemyjski** [comment]
Thanks for your commit!

**Comment by niemyjski** [comment]
We are in the process of pushing [v3.1.0](https://github.com/exceptionless/Exceptionless.Net/releases/tag/v3.1.0) out to NuGet!
