### ISSUE TITLE
exceptionless does not report corrupted state exceptions

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#201]
Hi,

There is no reporting method in the exceptionless code base marked with the `HandleProcessCorruptedStateExceptions` attribute, so all corrupted state exceptions won't be reported and such critical issues could be silently ignored.

Do you plan to manage corrupted state exceptions in a future version of exceptionless?

Thanks.

**Comment by niemyjski** [comment]
Is there any chance you can add this to our client in a pr and then try it out in your app for a little while and see if you see an adverse affects.

**Comment by niemyjski** [comment]
I was trying to find usages of that attribute. I seen your example and went and looked at their error client and they don't even use that attribute.

**Comment by CyberSinh** [comment]
As requested, the Airbrake article has been provided only to show you how to trigger artificial AccessViolationException.

[Logify WPF client](https://github.com/DevExpress/Logify.Alert.Clients/blob/d53631eccc8c663f7bfc9ada96968b8ae610cf65/dotnet/Logify.Alert.Wpf/LogifyClient.cs) uses this attribute. It was when I discovered that Logify was reporting exceptions that exceptionless was unable to do that I realized the problem.

In my app, for better flexibility, I manually catch unhandled exception before sending logs via exceptionless (so without using the ExceptionlessClient.Register method).

**Comment by niemyjski** [comment]
Can you research this some more. It seems that these need to be placed on the handlers of Dispatcher and AppDomain unhandled. Are there any others?

```cs
[SecurityCritical]
[HandleProcessCorruptedStateExceptions]
```

Also, We are registering these handlers in a static extension method. I'm not sure the best way to apply these attributes. Currently we are defining a delegate inline and applying it. If you have any ideas please let me know. 

One potential issue we have with the current solution is that we only ever create one delegate that's wrapped with the first exceptionless client instance. If you have two clients and call Register. It will be tied to the first instance :\

**Comment by CyberSinh** [comment]
It is necessary to extract the method of the event handler in class to be able to apply the `[HandleProcessCorruptedStateExceptions]` attribut. But as this event handler uses an `ExceptionlessClient` instance, using extension methods to register unhandled exceptions is probably not the appropriate solution.

**Comment by niemyjski** [comment]
Sorry for the delayed update on this, the holidays have been crazy. Is there any chance you want to take a stab at a pr for this?

**Comment by CyberSinh** [comment]
Sorry, but I don't have much time for a PR right now.

**Comment by niemyjski** [comment]
@CyberSinh sorry this still hasn't been resolved, where you able to find a fix for this?

**Comment by CyberSinh** [comment]
No need now. Even though this attribute exists in .NET Core, since the recovery from corrupted process state exceptions is not supported, the attribute `HandleProcessCorruptedStateExceptions` is ignored. The CLR doesn't deliver corrupted process state exceptions to the managed code.
