### ISSUE TITLE
Exceptionless.AspNetCore Usage Outside Middleware

### ISSUE THREAD

**Issue by moogle001** [exceptionless/Exceptionless.Net#204]
The project Exceptionless.AspNetCore is of limited use for two reasons:

1. Several classes are marked internal, preventing their reuse outside of ExceptionlessMiddleware.

2. ExceptionlessAspNetCorePlugin relies on context.ContextData.SetHttpContext having been called in order to obtain request and session info. When using Exceptionless.Extensions.Logging or Serilog.Sinks.Exceptionless, this method will not be called.

**Comment by moogle001** [comment]
Created a pull request #205.

**Comment by niemyjski** [comment]
This has been merged in! Thanks!!
