### ISSUE TITLE
serilog-sinks-exceptionless: Where does the HttpContext come from?

### ISSUE THREAD

**Issue by SeppPenner** [exceptionless/Exceptionless.Net#208]
I know, that this is the wrong project. However, the other one does not allow to create issues.

In the https://github.com/serilog/serilog-sinks-exceptionless project:

What does the code `.AddRequestInfo(HttpContext)` in the example do and where does the `HttpContext` come from?

```csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.Exceptionless(b => b.AddTags("ASP.NET Core Example Logger").AddRequestInfo(HttpContext))
    .CreateLogger();
```

**Comment by SeppPenner** [comment]
I mean: The example is quite irritating because the easiest way would be:

```csharp
Log.Logger = new LoggerConfiguration()
            .WriteTo.Exceptionless(b => b.AddTags("ASP.NET Core Example Logger"))
            .CreateLogger();
```

**Comment by niemyjski** [comment]
We may need to update the readme, this isn't even needed anymore in an asp.net core application as we set the http context automatically when this is called (https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Platforms/Exceptionless.AspNetCore/readme.txt#L54). 

But in the above that is an Extension method and it was just an example of how you could call it from say a Controller. But it doesn't make sense for sewing up. a new logger like this. Would you mind doing a pr for this.

**Comment by SeppPenner** [comment]
@niemyjski It's there: https://github.com/serilog/serilog-sinks-exceptionless/pull/8
