### ISSUE TITLE
Exceptionless Client Configuration update interval setting

### ISSUE THREAD

**Issue by wtx2043pp986** [exceptionless/Exceptionless.Net#212]
Hello, 

I' ve followed the instruction below here: https://github.com/exceptionless/Exceptionless.Net/wiki/Client-Configuration-Values#updating-client-configuration-settings

I know the default update time interval is 2 minutes,  and then I tried to change the value as 5 seconds, but it seems not work.

```
ExceptionlessClient.Default.Configuration.UpdateSettingsWhenIdleInterval = TimeSpan.FromSeconds(5);
```

Please help, thanks.

**Comment by ejsmith** [comment]
Can you tell us more about what you are doing and what you are expecting to happen?

**Comment by wtx2043pp986** [comment]
@ejsmith I 'm trying to set update interval to 5 seconds, and hoped it would notify my client side setting(https://github.com/exceptionless/Exceptionless.Net/wiki/Client-Configuration-Values#subscribing-to-client-configuration-setting-changes)
But when I did it and updated client configuration from Exceptionless Server, it still delayed 2 minites on calling my subscribing method.(default update interval).

Did I make something mistake?

**Comment by niemyjski** [comment]
You can't set a period less than 2 minutes. https://github.com/exceptionless/Exceptionless.Net/blob/997e8f0b3716acab9f21eee13f16a354c5b74458/src/Exceptionless/Configuration/ExceptionlessConfiguration.cs#L195. If you need it updated immediately (it will happen within 5 seconds after startup), you can call SettingsManger.UpdateSettings. Is there a specific use case where you need settings quicker? If you submit an event and have old settings, new settings will be retrieved automatically.

**Comment by wtx2043pp986** [comment]
@niemyjski I got it, Thanks a lot!
