### ISSUE TITLE
Can't mock ExceptionlessClient.Default

### ISSUE THREAD

**Issue by bsimser** [exceptionless/Exceptionless.Net#213]
Hi guys,

All of the documentation suggests a common way to log exceptions in a .NET client:

`ExceptionlessClient.Default.CreateLog(...)`

This is fine but trying to write unit tests for controllers where we log navigation information (or any use of ExceptionlessClient.Default) seems to be impossible (using Moq).

For example here's a simple controller:

```
class MyController : Controller
{
  public ActionResult Index()
  {
    ExceptionlessClient.Default.CreateLog("Navigation", "Home Page", LogLevel.Info).AddObject(User.Identity).Submit();
    return View();
  }
}
```

Trying to write a simple test for this:

```
[TestFixture]
class TestController
{
  [Test]
  public void TestIndex()
  {
    var controller = new MyController();
    var result = controller.Index() as ViewResult;
    Assert.IsNotNull(result);
  }
}
```

NOTE: I'm not trying to write tests to make sure Exceptionless is called. I assume it works. The problem is that we have calls to ExceptionlessClient.Default all over the place so it makes for writing unit tests against this code difficult. Yes, there are a lot better ways to log exceptions but this is what we have to work with so without replacing all of the ExceptionlessClient calls with our own custom client, how do you unit test something like this with Moq? The other suggestion is to use something like TypeMock or something that can mock out static properties but I don't want to introduce another tool for this. Maybe this isn't something that can be done giving the constraints (ExceptionelessClient.Default, Moq, etc.)

Not sure what to do here. Discussions with Eric suggest registering a different implementation of ISubmissionClient but that doesn't seem to address the issue that ExceptionlessClient.Default is a static property and the ISubmissionClient just lets you implement the PostEvents calls. How does this help with trying to unit test the controller using the suggested use for logging messages?

**Comment by ejsmith** [comment]
I just tried doing this and it worked fine other than `User.Identity` being null which is going to be true in a test like this since there isn't a real user being flowed through the controller. Is that the problem you are seeing or are you seeing something else?

**Comment by bsimser** [comment]
Can you post what you tried? Obviously I'm missing something simple (how the Mock is setup, etc.). Or are you just letting the client run in a test as-is (so the test would actually submit something).

**Comment by niemyjski** [comment]
I haven't tried it but what I would do is Mock the ISubmissionClient or the IEventQueue and then inject it into the client.Configuration then you can verify that submission has been called when either an event is enqueued or ProcessQueue has been called. Alternatively, you could inject a new plugin and just assert a counter has been incremented.

**Comment by bsimser** [comment]
@niemyjski sure and again I would look at doing this but the code that exists, that you guys prescribe as to how to use the library and submit exceptions, doesn't seem to support that. Again I might be wrong here and missing something obvious but in our code we use the documented methods for submitting log messages:

```
ExceptionlessClient.Default.CreateLog("Navigation", "Home Page", LogLevel.Info).Submit();
```

In the ExceptionlessClient source Default is created for you so there's nowhere I see, without extensively re-implementing the client calls like you see above, being able to inject a custom client (whether it's for testing or in the application).

I admit using the static property isn't great but it's what your documentation directs people to. A custom client, custom configurations, etc. would all be great but that means going through everywhere and re-implementing it with that custom client/configuration.

The question is how do I mock out the ExceptionlessClient.Default for testing? If the answer is to build your own custom client/custom configuration that's fine and it means any code we have where we used this is un-testable (until we replace it with a custom client). If that's the case I would suggest you guys provide some guidance on how to write create an ExceptionlessClient that is testable and what's needed to make it work. If there's another way through configuration (without changing the in-place calls to ExceptionlessClient.Default) then I'm all for it, I just don't see how it's done.

**Comment by niemyjski** [comment]
I somewhat feel like we are in the same boat as this: https://indexoutofrange.com/Stop-trying-to-mock-the-ILogger-methods/#.XUl5zUEZNsA.twitter In fact, I try not to use our client directly in code and use an abstraction like ILogger. Let's say you are doing: `ExceptionlessClient.Default.CreateLog("Navigation", "Home Page", LogLevel.Info).Submit();` You could easily do `ILoggerInstance.LogInformation("Navigation").SetTag("Home Page");` which gives you way more benefits like you can log anywhere including exceptionless. And I like the article above..

Regardless, if you wanted to inject your own thing you could do `ExceptionlessClient.Default.Configuration.Resolver.Register<ISubmissionClient>(your mocked client).` You could also inject your own exceptionless client into things and then mock it that way, you'd just have to be sure to pass that instance to any `ex.ToExceptionless(myinjectedinstance)` but again I'd rather just do `ILoggerInstance.LogError(ex, "blah")` and get the same thing. I hope this helps.

I think the easiest of all the approaches would be to just add your own plugin by mocking a plugin, adding to it the default client instance with a low priority and then checking state on that plugin. https://github.com/exceptionless/Exceptionless.Net/wiki/Adding-Plugins

I'd love your feedback on the above.

**Comment by ejsmith** [comment]
@bsimser I just created a unit test project from the code you sent me. The test passed with the only assert that you had in it because it just went over the `CreateLog` call and the controller method returned a value. Again, the only problem I had was that the code you sent is making the assumption that User is not null which it will be in your test code you sent since it's not invoking all of the normal ASP.NET Core pipeline to populate the User. But that isn't anything to do with Exceptionless. What am I missing?

**Comment by ejsmith** [comment]
I created this test to try it: https://github.com/exceptionless/Exceptionless.Net/blob/6e05f347973fc6d9482ed8e192aa371cb33feb85/test/Exceptionless.Tests/Configuration/ControllerTests.cs#L20

**Comment by niemyjski** [comment]
What is the outcome of this issue? Can it be closed or is there something we need to do to make this easier?

**Comment by bsimser** [comment]
Thanks.
