### ISSUE TITLE
ExceptionlessMiddleware always "Unable to get POST data: The stream could not be reset."

### ISSUE THREAD

**Issue by hihipp** [exceptionless/Exceptionless.Net#217]
# Version
Exceptionless.AspNetCore 4.3.4

# Problem
[RequestInfoCollector.cs](https://github.com/exceptionless/Exceptionless.Net/blob/v4.3.4/src/Platforms/Exceptionless.AspNetCore/RequestInfoCollector.cs)
``` C#
if (!context.Request.Body.CanSeek) {
    string message = "Unable to get POST data: The stream could not be reset.";
    log.Debug(message);
    return message;
}

long originalPosition = context.Request.Body.Position;
if (originalPosition > 0) {
    context.Request.Body.Position = 0;
}
```

# Description
.net core Request.Body is stream of type FrameRequestStream and it doesn’t support seeking.

**Comment by niemyjski** [comment]
I. think you may need to enable buffering (https://devblogs.microsoft.com/aspnet/re-reading-asp-net-core-request-bodies-with-enablebuffering/). Can you try this and see if it works, We may need to update the readme and wiki for this (as there might be a performance overhead for enabling this).

**Comment by hihipp** [comment]
EnableBuffering, it works fine, thanks.
