### ISSUE TITLE
ApiKey can't be changed after the client has been initialized.

### ISSUE THREAD

**Issue by bladefist** [exceptionless/Exceptionless.Net#22]
This occurs when the autostart property of IIS is enabled (IIS 8 and MVC 5).
```
[ArgumentException: ApiKey can't be changed after the client has been initialized.]
   Exceptionless.ExceptionlessConfiguration.set_ApiKey(String value) +127
   Exceptionless.ExceptionlessExtraConfigurationExtensions.ReadFromConfigSection(ExceptionlessConfiguration config) +224
   Exceptionless.ExceptionlessExtraConfigurationExtensions.ReadAllConfig(ExceptionlessConfiguration config, Assembly[] configAttributesAssemblies) +232
   Exceptionless.ExceptionlessClientExtensions.Startup(ExceptionlessClient client, AppDomain appDomain) +82
   Exceptionless.Mvc.ExceptionlessModule.Init(HttpApplication app) +43
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +530
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): ApiKey can't be changed after the client has been initialized.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12979668
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12819261
```

**Comment by niemyjski** [comment]
Thanks for reporting this.. I'm going to start taking a look into this. In the mean time can you try disabling auto start and see if that fixes this behavior.

**Comment by niemyjski** [comment]
@ejsmith Can you please review this change.

@bladefist, I wasn't able to reproduce but I believe this fix and my previous commit will resolve this issue. Once a code review has been completed I'll push out a new build for you to try.

**Comment by niemyjski** [comment]
@bladefist, would you mind trying a nightly build of [MyGet](https://www.myget.org/F/exceptionless/api/v2)? It only has this change since the last time we pushed. It would be great to see if this is fixed before we push a new build.

**Comment by niemyjski** [comment]
@bladefist, After further review I've pushed this new NuGet Package: 1341 Please let me know if this does not fix this issue by commenting on this issue.

**Comment by niemyjski** [comment]
We are in the process of pushing [v3.1.0](https://github.com/exceptionless/Exceptionless.Net/releases/tag/v3.1.0) out to NuGet!
