### ISSUE TITLE
How to register app.UseExceptionless("key") in .net core2.1 IHostBuilder?

### ISSUE THREAD

**Issue by wmowm** [exceptionless/Exceptionless.Net#229]
.net core2.1 IHostBuilder does not have IApplicationBuilder, how can I register the service to the application?

**Comment by niemyjski** [comment]
@wmowm how are you wanting to configure via the IHostBuilder builder. I just created multiple apps using the .net 3.1 sdk and both had the `IApplicationBuilder`. Just trying to get your expectations.
