### ISSUE TITLE
UWP Configuration

### ISSUE THREAD

**Issue by mariohik** [exceptionless/Exceptionless.Net#230]
How can I configure an UWP application?
I'm calling ExceptionlessClient.Default.Startup on my App Initialization.
It works on DEBUG mode but when I move to RELEASE, I got an error:

`
System.PlatformNotSupportedException: Operation is not supported on this platform.
`

**Comment by niemyjski** [comment]
![image](https://user-images.githubusercontent.com/1020579/78675586-e29dfe80-78aa-11ea-848f-81fbcaa9995d.png)

I created a new sample uwp app and ran it in both debug mode and release mode and could submit an event using the latest nightly build. Can you please try the latest nightly and see if you are still seeing this behavior.

**Comment by mariohik** [comment]
Using the latest nightly build I could ran my application in debug and release mode and submit an exception.
Thank you!

**Comment by niemyjski** [comment]
I just pushed https://github.com/exceptionless/Exceptionless.Net/releases/tag/v4.4.0
