### ISSUE TITLE
No problem, but no data，Why?

### ISSUE THREAD

**Issue by woshilangdanger** [exceptionless/Exceptionless.Net#232]
the exceptionless server had run, elasticsearch is ok
when i use then excetionless client for .netcore,this is no data  added

**Comment by niemyjski** [comment]
Have you checked the client logs to see what it says, maybe it cannot connect? https://github.com/exceptionless/Exceptionless.Net/wiki/Troubleshooting#enable-client-logging

**Comment by woshilangdanger** [comment]
> Have you checked the client logs to see what it says, maybe it cannot connect? https://github.com/exceptionless/Exceptionless.Net/wiki/Troubleshooting#enable-client-logging

this is the log's description :
2020-07-09 10:37:58.1002 Info  DefaultEventQueue: Sent 1 events to "http://192.168.0.42:3008".
the api url is http://192.168.0.42:3008 
this is my configuration:
 ExceptionlessClient.Default.Configuration.ApiKey = "LXlGPR2wTSTL8UfXRsMn1dz2s1CrSVmd8PlwUHWv";
 ExceptionlessClient.Default.Configuration.ServerUrl = "http://192.168.0.42:3008";
 ExceptionlessClient.Default.Configuration.UseFileLogger("E:\\WorkingGitLab\\exceptionless.log");
 app.UseExceptionless(ExceptionlessClient.Default);
i think it's ok
i used the exceptionless.ui  and it's ok. 	
I can  create an organization and project successfully.
Still, this is no data in exceptionless

**Comment by niemyjski** [comment]
Are you running the jobs in process or out of process? What does the event posts jobs log say?

**Comment by ejsmith** [comment]
@woshilangdanger in the UI in the project configuration page, you can pick shell and it will show the bash / powershell commands to send an event to the server. Can you try that and see if it works? If that works then it's definitely a client configuration issue. @niemyjski do we require anything like `api/v2` at the end of the ServerUrl setting?

**Comment by woshilangdanger** [comment]
> Are you running the jobs in process or out of process? What does the event posts jobs log say?

yes,i find the error.
options.EnableMapperSizePlugin = pairs.GetValueOrDefault("enable-size-plugin", appMode != AppMode.Development);
i find a error about mapper-size,beacuse elasticseach was not install the plugin of mapper-size ,and now it's ok 
thanks a lot~

**Comment by niemyjski** [comment]
Thanks for the update. If you use our docker image it's pre configured!
