### ISSUE TITLE
Use of EnableSSL in ExceptionlessAttribute?

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.Net#24]
If serverurl starts with https -> enable ssl automatically? This seems like a useless property to me.

**Comment by niemyjski** [comment]
EnableSSL is true by default. It's only set to false via the attribute or server configuration. We could be smarter about this I think.

@ejsmith do you think we should deprecate this attribute (removing it would break people but something we could do in v4).

**Comment by niemyjski** [comment]
I'm closing this as we made a change a month ago that got rid of this functionality (we now use the serverurl to detect https). We also marked the EnableSSL setting as Obsolete
