### ISSUE TITLE
NLog plugin minLevel not work

### ISSUE THREAD

**Issue by jol5** [exceptionless/Exceptionless.Net#244]
```
// Test NLog
            var config = new LoggingConfiguration();
            var exceptionlessTarget = new ExceptionlessTarget();
            config.AddTarget("exceptionless", exceptionlessTarget);
            config.LoggingRules.Add(new LoggingRule("*", global::NLog.LogLevel.Debug, exceptionlessTarget));
            LogManager.Configuration = config;

            var logger = LogManager.GetCurrentClassLogger();
            logger.Warn()
                .Message("App Starting...")
                .Tag("Tag1", "Tag2")
                .Property("LocalProp", "LocalValue")
                .Property("Order", new { Total = 15 })
                .Write();
```
follow code only warn,error log
will send to Exceptionless

ENV:
netcore 3.1
NLog 4.7.7
Exceptionless.NLog 4.6.2
![image](https://user-images.githubusercontent.com/28615922/106566738-adfee000-656b-11eb-8249-279deab389d3.png)

**Comment by niemyjski** [comment]
Hello,

Thanks for reaching out to us! 

- [ ] Have you tried turning on diagnostic logs locally and seeing what is occurring in the logs? https://exceptionless.com/docs/clients/dotnet/troubleshooting/#enable-client-logging
- [ ] Did you set the DefaultMinLevelLog in configuration which sets a default until server settings are defined? https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Configuration/ExceptionlessConfiguration.cs#L213
- [ ] Do you have warning as your project level default log level or for this specific stack? https://exceptionless.com/docs/setting-log-levels/

**Comment by niemyjski** [comment]
This should work if you remove the api key from the nlog config section. When you specify an api key there it uses an internal Exceptionless client instance. Does this fix this issue?

**Comment by samchenws** [comment]
> This should work if you remove the api key from the nlog config section. When you specify an api key there it uses an internal Exceptionless client instance. Does this fix this issue?

OK, it works.
Thank you very much.
