### ISSUE TITLE
Framework 4.6 log4net only records the error log

### ISSUE THREAD

**Issue by knowyi** [exceptionless/Exceptionless.Net#245]
Hello, my log4net can upload all log level logs in NETCORE environment. Historical project or framework version 4.6, but only error logs can be uploaded. What's the difference?

![image](https://user-images.githubusercontent.com/7392434/109252834-6ba68700-7829-11eb-8f6b-90f3c1c49f1b.png)

<?xml version="1.0" encoding="utf-8" ?>
<log4net debug="true">
	<appender name="DebugAppender" type="log4net.Appender.RollingFileAppender">
		<filter type="log4net.Filter.LevelRangeFilter">
			<levelMin value="DEBUG" />
			<levelMax value="DEBUG" />
		</filter>
		<file value="D:\logs\testProduct\\debug.txt" />
		<appendToFile value="true" />
		<rollingStyle value="Date" />
		<datePattern value="yyyyMMdd" />
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%date [%thread] %-5level %logger - %message%newline" />
		</layout>
	</appender>
	<appender name="LogAppender" type="log4net.Appender.RollingFileAppender">
		<filter type="log4net.Filter.LevelRangeFilter">
			<levelMin value="INFO" />
			<levelMax value="INFO" />
		</filter>
		<file value="D:\logs\testProduct\\log.txt" />
		<appendToFile value="true" />
		<rollingStyle value="Date" />
		<datePattern value="yyyyMMdd" />
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%date [%thread] %-5level %logger - %message%newline" />
		</layout>
	</appender>
	<appender name="ExceptionAppender" type="log4net.Appender.RollingFileAppender">
		<filter type="log4net.Filter.LevelRangeFilter">
			<levelMin value="WARN" />
			<levelMax value="FATAL" />
		</filter>
		<file value="D:\logs\testProduct\\Error.txt" />
		<appendToFile value="true" />
		<rollingStyle value="Date" />
		<datePattern value="yyyyMMdd" />
		<layout type="log4net.Layout.PatternLayout">
			<conversionPattern value="%date %message%newline" />
		</layout>
	</appender>
	<appender name="exceptionless" type="Exceptionless.Log4net.ExceptionlessAppender,Exceptionless.Log4net" />
	<root>
		<level value="ALL" />
		<appender-ref ref="DebugAppender" />
		<appender-ref ref="LogAppender" />
		<appender-ref ref="ExceptionAppender" />
		<appender-ref ref="exceptionless"/>
	</root>
</log4net>

**Comment by niemyjski** [comment]
I'm not sure why you are seeing different minimum levels. There are no code differences between our NET 4.5+ client and our .NET Core clients (it's the same code base). Can you please share a snippet of how you are configuring your logger and exceptionless client. If you could provide a github repo with a minimal sample I would be more than happy to debug it.

Here is a link to the source for the client implementation if you are curious: https://github.com/exceptionless/Exceptionless.Net/tree/master/src/Platforms/Exceptionless.Log4net

**Comment by niemyjski** [comment]
Were you able to narrow down this issue?
