### ISSUE TITLE
The FolderObjectStorage class SaveObject<T>method has a issues

### ISSUE THREAD

**Issue by d18zj** [exceptionless/Exceptionless.Net#246]
When log level is changed from DEBUG to INFO, The client-side **server-settings.json** file will be incorrect.
``

{"@@UserAgentBotPatterns":"*bot*,*crawler*,*spider*,*aolbuild*,*teoma*,*yahoo*","@@log:*":"debug"}
``

After the update, there is an additional **}** sign at the end

`{"@@UserAgentBotPatterns":"*bot*,*crawler*,*spider*,*aolbuild*,*teoma*,*yahoo*","@@log:*":"info"}}`

should modify FolderObjectStorage.cs like this:
![image](https://user-images.githubusercontent.com/4657391/110778738-b4385880-829d-11eb-98b5-eba82dba1061.png)

**Comment by niemyjski** [comment]
Thanks for this report and nice find! I wonder why we did OpenWrite there. Is there any chance you could create a test and submit this change in a pr?
