### ISSUE TITLE
Debug and INFO level logs are not displayed  

### ISSUE THREAD

**Issue by 1301536601** [exceptionless/Exceptionless.Net#259]
--Version
exceptionless/api:6.0.0
exceptionless/job:6.0.0
exceptionless/ui:2.9.2
exceptionless/elasticsearch:7.5.2
kibana:7.5.2

--- Code configuration
Startup configuration
![image](https://user-images.githubusercontent.com/33918700/122180047-aa387e00-ceba-11eb-9054-b077c74b64b5.png)

Program configuration
![image](https://user-images.githubusercontent.com/33918700/122180102-b6244000-ceba-11eb-97d6-ccd88bddfbd8.png)

appsettings.json

![image](https://user-images.githubusercontent.com/33918700/122180361-f257a080-ceba-11eb-829d-a243fc43a258.png)

ExceptionlessUi Show
![image](https://user-images.githubusercontent.com/33918700/122180406-fa174500-ceba-11eb-8435-149b9e77653e.png)

log Record Code

![image](https://user-images.githubusercontent.com/33918700/122180614-2a5ee380-cebb-11eb-98c5-18636f8880c8.png)

I wonder why only the logs of WARNING and ERROR are logged in my project ，Can you give me some ideas?

**Comment by niemyjski** [comment]
Hello,

Can you please try setting: `ExceptionlessClient.Default.Configuration.SetDefaultMinLogLevel(LogLevel.Debug)`  https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Configuration/ExceptionlessConfiguration.cs#L213 I'm thinking your log levels are being ignored by the default settings until sever settings are retrieved.

**Comment by 1301536601** [comment]
> Hello,
> 
> Can you please try setting: `ExceptionlessClient.Default.Configuration.SetDefaultMinLogLevel(LogLevel.Debug)` https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Configuration/ExceptionlessConfiguration.cs#L213 I'm thinking your log levels are being ignored by the default settings until sever settings are retrieved.


Thank you for fixing the current issue after setting the log level

**Comment by niemyjski** [comment]
Thanks for the update. @ejsmith we may want to tweak this or add something to the readmes as I've been asked this quite a few times.
