### ISSUE TITLE
I can receive Error level data, but I cannot receive infomation level log data (exceptionless.Nlog used)

### ISSUE THREAD

**Issue by CoderRiker** [exceptionless/Exceptionless.Net#261]
![image](https://user-images.githubusercontent.com/88869889/130884710-5f9ec104-c78b-4eac-adac-6ed7a0bd7de7.png)
This is my Nlog configuration file

**Comment by CoderRiker** [comment]
I have elevated the project permissions to full control, but nothing seems to be written to the exceptionless.log file.
And I made a simple demo and submitted log data of various levels, but only received data of Warning and above. code show as below:(Packages have been added: Exceptionless.NLog, NLog.Web.AspNetCore)

![image](https://user-images.githubusercontent.com/88869889/131213481-d6a26347-a435-430b-a5a3-b704350e1dfc.png)
Nlog.config:
`<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Debug">
	<extensions>
		<add assembly="Exceptionless.NLog"/>
		<add assembly="NLog.Web.AspNetCore"/>
	</extensions>
	<targets>
		
		
		
		
		<target xsi:type="Exceptionless" name="Exceptionless" apiKey="d5jRHzuqZUMtC6DKq33r3ZYk3w51WkRoLuBJmXhw"
				serverUrl="http://localhost:5010">
			
			<field name="StackTrace" layout="${stacktrace}"/>
			
			<field name="Message" layout="${message}"/>
			<field name="LogLevel" layout="${level}"/>
			<field name="CreateDate" layout="${date}"/>
			
			<field name="MachineName" layout="${machinename}" />
			
			<field name="ThreadId" layout="${threadid}"/>
			
			<field name="CallSite" layout="${callsite}"/>
			<field name="AppdomainVersion" layout="${assembly-version}"/>
			<field name="Appdomain" layout="${appdomain}"/> 
		</target>
		<target xsi:type="File" name="selflog"
				fileName="${basedir}\Nlogs\${level}s\${shortdate}${level}.log" encoding="utf-8"
				archiveEvery="Hour" archiveAboveSize="2097152"
				keepFileOpen="true" openFileCacheTimeout="30" openFileCacheSize="8"
				cleanupFileName =" false"
				layout="记录时间：${longdate} 日志级别：${uppercase:${level}} ${message} ${exception:format=tostring}" />
		
	</targets>
	<rules>
		
		<logger name="*" minlevel="Debug" writeTo="selflog" />
		
		<logger name='*' minlevel="Debug" writeTo='Exceptionless'/>
	</rules>
</nlog>`
Startrtup.cs:
![image](https://user-images.githubusercontent.com/88869889/131213601-405fd2f2-ed27-4ac7-811f-76930a9b1a3d.png)
![image](https://user-images.githubusercontent.com/88869889/131213643-d39aa695-fefc-4bab-980e-c54c9229b22c.png)
result:
![image](https://user-images.githubusercontent.com/88869889/131213741-acd476a0-43ce-4a95-8046-1a2f64ad84af.png)

How to solve it?

Because the company's project is relatively large, almost all project logs are used nlog. I need to get the parameter information based on the info information, so it is troublesome to find an alternative. I need your help. (*￣︶￣)

**Comment by CoderRiker** [comment]
> Please make sure you have write permission to that folder, your app may not have the permissions to write to that folder. For the xml node, you'd put that in your web.config if you are using ASP.NET (legacy)

![image](https://user-images.githubusercontent.com/88869889/131214148-77c451ce-74c1-4e33-8833-0d1bea3c4b4a.png)
This is the Exceptionless.web production environment console situation

**Comment by niemyjski** [comment]
It looks like the API key is wrong, you are getting a bunch of 401's
