### ISSUE TITLE
Exceptionles web module gets removed by Exceptionless.WebApi

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.Net#27]
To repro:

- Install Exceptionless.WebApi
- Install Exceptionless.Web into the same project
- Observe that the module is installed in the `<modules>` section in web.config
- Run `Update-Package -Reinstall Exceptionless.WebApi`
- Observe that the module is now gone

**Comment by srijken** [comment]
Looks like this happens through this path:
https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Platforms/WebApi/NuGet/tools/uninstall.ps1#L8
https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Shared/NuGet/tools/exceptionless.psm1#L130-L140

**Comment by niemyjski** [comment]
Do you think we should pass a parameter into remove saying the package name and then we can check that in the inner if.. I think this may be the best solution.

**Comment by niemyjski** [comment]
Thank you for your commit!
