### ISSUE TITLE
Sometimes pinvoke cannot work fine

### ISSUE THREAD

**Issue by pccai** [exceptionless/Exceptionless.Net#279]
web excepiton logs:
![LEK$K~)~(QF2KATD${SJ910](https://user-images.githubusercontent.com/2232794/169798793-ca26a0eb-01e8-4e3c-a423-9b78174a9d6e.png)

![image](https://user-images.githubusercontent.com/2232794/169798945-22ef3635-9597-482c-84a2-4fdf0996ca4c.png)

**Comment by pccai** [comment]
.net 5.0.407

**Comment by niemyjski** [comment]
@pccai looking at this, this is all try caught, are you seeing an unhandled exception? How is this getting logged out? Also, I'd recommend upgrading to .NET 6 as .NET 5 is EOL.

**Comment by niemyjski** [comment]
@pccai did this help?

**Comment by pccai** [comment]
yes, fixed!
When used pinvoke, i missing a statement:  hLib = (IntPtr)0; in constructed function.
tks.
