### ISSUE TITLE
Add support for ASP.NET Core

### ISSUE THREAD

**Issue by barranger** [exceptionless/Exceptionless.Net#28]
I realize that it's still in preview/beta, but as it stands any project using vNext, cannot use Exceptionless

**Comment by niemyjski** [comment]
This is something we really want as well. We are planning on releasing and porting the server to vnext after it's released as well. Yesterday I went to Build Chicago and asked some of the employees / mvps how we can do this and they were all stumped. I think we can use VS multi-targeting to do this. But then again... I'm wondering however, if we should just create a new NuGet package for this. What do you think would be a good name for this?

**Comment by barranger** [comment]
I wonder if creating a temp NuGet package (named Exceptionless.vNext) at least until MS does the official release (which I'm assuming will include a way to properly multi-target)?

**Comment by niemyjski** [comment]
Do you know what others are naming their vnext packages?

**Comment by barranger** [comment]
I don't, sorry

**Comment by niemyjski** [comment]
@barranger Have you had any luck writing a client for vnext?

**Comment by hmvs** [comment]
Any news? We started writing new project on asp.net core 1.0. Have you tried to integrate exceptionless for web api?

**Comment by rbaz** [comment]
Hi Vadim,
Well, I have quit my job. I have no idea if the plug-in keep used or not.
thank's.




2016-04-25 4:02 GMT-04:00 Vadim Kurachevsky <notifications@github.com>:

> Any news? We started writing new project on asp.net core 1.0. Have you
> tried to integrate exceptionless for web api?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/exceptionless/Exceptionless.Net/issues/28#issuecomment-214196723>
>



-- 
Cordialement.

................

*Bouazza Rochdi (B.Ing)*
*Consultant .Net *
*+(514)-326-0315*

**Comment by hmvs** [comment]
Hi,  @rbaz.
Thanks for the answer.
Will wait for comment from @niemyjski

**Comment by niemyjski** [comment]
We are looking to migrate everything to the new project format and add support for .net core. However, we are waiting until rc2 before even starting as there are so many breaking changes and all the tooling has changed between rc1 and rc2. If someone wants to start working on it we can help out but I think it's best to wait for rc2.

**Comment by hmvs** [comment]
I see. Would be great if you can try to integrate current version of exceptionless to the rc1 web api project and post a sample. For dnx451 as target. 
Thanks

**Comment by niemyjski** [comment]
@hmvs Can you take a stab at this and let us know? I'm just worried that we may be waisting our time on rc1 as we know so many things have changed (apis and tooling). I mean one could look at rc2 nightlies I don't know how locked down they are but they said the tooling is 3-6 weeks out.

**Comment by ejsmith** [comment]
I feel like we should wait for rc2. Unless someone wants to take a stab at it.

**Comment by niemyjski** [comment]
We have a public slack channel here: http://slack.exceptionless.com if you want to join and chat about .net core.

**Comment by rbaz** [comment]
Hello Vadim,
What's new I have sometimes. What can I do?
Thanks.


2016-04-25 10:51 GMT-04:00 Blake Niemyjski <notifications@github.com>:

> We have a public slack channel here: http://slack.exceptionless.com if
> you want to join and chat about .net core.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/exceptionless/Exceptionless.Net/issues/28#issuecomment-214371627>
>



-- 
Cordialement.

................

*Bouazza Rochdi (B.Ing)*
*Consultant .Net *
*+(514)-326-0315*

**Comment by niemyjski** [comment]
@rbaz I think it's best to start on upgrading the project to the new project format using rc2 bits (not sure how that's sitting).

**Comment by ejsmith** [comment]
Yeah, we've been waiting for RC2 to start because of all the churn.

**Comment by rbaz** [comment]
Ok, I will look for that this week!

**Comment by ejsmith** [comment]
Yeah, I think they are very close to releasing it.

**Comment by rbaz** [comment]
Ok, I took a look for that. And I think  I will beginning to create the
structure for the project -- Solution --- Class Librairie -- projects test
and ...
After that we will wait for the RC2.
I think is safe like this.



2016-05-04 14:41 GMT-04:00 Eric J. Smith <notifications@github.com>:

> Yeah, I think they are very close to releasing it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/exceptionless/Exceptionless.Net/issues/28#issuecomment-216961187>
>



-- 
Cordialement.

................

*Bouazza Rochdi (B.Ing)*
*Consultant .Net *
*+(514)-326-0315*

**Comment by hmvs** [comment]
Hi guys, RC2 released :)

**Comment by rbaz** [comment]
Hi,
Yeah!

2016-05-17 3:46 GMT-04:00 Vadim Kurachevsky <notifications@github.com>:

> Hi guys, RC2 released :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/exceptionless/Exceptionless.Net/issues/28#issuecomment-219643578>
>



-- 
Cordialement.

................

*Bouazza Rochdi (B.Ing)*
*Consultant .Net *
*+(514)-326-0315*

**Comment by niemyjski** [comment]
Yeah! I'm excited

**Comment by niemyjski** [comment]
@ejsmith not sure if the first step is to upgrade everything to the new project format or just the new project we will create. Might be a good idea to upgrade everything (some things might change after release but I think we might be good (https://github.com/aspnet/Home/issues/1451). Appveyor will be updating there base images real shortly with the new dotnet cli but looks like all the appveyor scripts change (http://help.appveyor.com/discussions/questions/2249-how-to-use-latest-dotnet-cli).

@bartmax was kind enough to start upgrading foundation: https://github.com/exceptionless/Foundatio/pull/44 there are some notesin there  

Does someone want to start on just converting to the new project format so we can get our build and ci's going and then iterate from there? This would be a huge help.

**Comment by niemyjski** [comment]
I'm working on this starting right now!

**Comment by niemyjski** [comment]
I just wanted to let you know that we have the client written in the netstandard branch and we should be pulling it into master soonish.

We'd love your feedback on the client.. You should be able to get the latest prerelease client from the following nuget feed: https://ci.appveyor.com/nuget/exceptionless-net

**Comment by niemyjski** [comment]
​Hey, I wanted to let you know that we have a nightly build which is stable and will become a beta release. It's on nuget as a prerelease v4 build. It's a major version because we got rid of the portable package and merged everything in to the Exceptionless package and made it pcl + .net standard.  Please feel free to update your nuget packages to this release and let us know about any issues.  If you want just core clr support install the Exceptionless package, if you want asp.net core support please install the Exceptionless.AspNetCore package :) and follow the readme. Please let us know if you have any feedback or run into any issues.

**Comment by niemyjski** [comment]
A beta is now available: https://github.com/exceptionless/Exceptionless.Net/releases/tag/v4.0.0-beta

**Comment by niemyjski** [comment]
Has anyone had a chance to try the beta? I'd love your feedback.

**Comment by hmvs** [comment]
Will try to integrate it on monday. Our first product on asp.net core close to release so as usual we will integrate exceptionless into it. 
Thanks for the efforts.

**Comment by niemyjski** [comment]
https://exceptionless.com/exceptionless-4-0-net-core-asp-net-core-support/ It has shipped! Let me know if you run into any issues.

**Comment by hmvs** [comment]
Seems we integrated, and working fine :) Thanks

**Comment by VQuery** [comment]
How to specify the server URL in .netcore as like api key?

app.exceptionless("Apikey");

**Comment by hmvs** [comment]
@VQuery 
There is no such overload. Instead, you can create Exceptionless client on your own and use it. 

Option 1: 
```
    ExceptionlessClient.Default.Configuration.ServerUrl = "http://your-url.com";
            ExceptionlessClient.Default.Configuration.ApiKey = "http://your-url.com";
            
            app.UseExceptionless(ExceptionlessClient.Default);
```

Option 2: 

```
          app.UseExceptionless(new ExceptionlessClient(c => {
	            c.ApiKey = "key";
	            c.ServerUrl = "http://your-url.com";
            }));
```

I believe `option 1` is more preferable because you can use the default client.
