### ISSUE TITLE
Update NLog ExceptionlessTarget to use Layout for ApiKey and ServerUrl

### ISSUE THREAD

**Issue by snakefoot** [exceptionless/Exceptionless.Net#297]
Change these lines:

https://github.com/exceptionless/Exceptionless.Net/blob/17841c9b07858cb3aa5f5f4d5cf038afff5a7bf2/src/Platforms/Exceptionless.NLog/ExceptionlessTarget.cs#L12-L13

To these lines:

```c#
 public Layout ApiKey { get; set; } 
 public Layout ServerUrl { get; set; } 
```

Then update `InitializeTarget()`

```c#
        protected override void InitializeTarget() {
            base.InitializeTarget();

            var apiKey = RenderLogEvent(ApiKey, LogEventInfo.CreateNullEvent());
            var serverUrl = RenderLogEvent(ServerUrl, LogEventInfo.CreateNullEvent());

            if (!String.IsNullOrEmpty(apiKey) || !String.IsNullOrEmpty(serverUrl))
                _client = new ExceptionlessClient(config => {
                    if (!String.IsNullOrEmpty(apiKey) && apiKey != "API_KEY_HERE")
                        config.ApiKey = apiKey;
                    if (!String.IsNullOrEmpty(serverUrl))
                        config.ServerUrl = serverUrl;
                    config.UseInMemoryStorage();
                });
        }
```
This will enable[ NLog Target Configuration](https://github.com/NLog/NLog/wiki/Layouts#target-configuration-with-layout) where settings can be retrieved from app.config or appsettings.json (making it easier to have environment-specific setups)

**Comment by snakefoot** [comment]
Example:
```xml
    <target xsi:type="Exceptionless, Exceptionless.NLog" name="exceptionless" apiKey="${configsetting:Exceptionless.ApiKey}">
      <field name="host" layout="${machinename}" />
      <field name="process" layout="${processname}" />
    </target>
```
Then in `appsettings.json`:
```json
{
    "Exceptionless":{
        "ApiKey":"API_KEY_HERE"
    }
}
```

See also: https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer

P.S. You should update the [ReadMe.txt](https://github.com/exceptionless/Exceptionless.Net/blob/main/src/Platforms/Exceptionless.NLog/readme.txt) example to no longer include this:
```xml
<field name="windows-identity" layout="${windows-identity:userName=True:domain=False}" />
```
As it requires additional nuget-package with NLog v5, and not supported on all platforms (Ex. Linux).

**Comment by niemyjski** [comment]
I guess it wouldn't hurt to support this but I am on the fence with your api key example. Users shouldn't set the api key on an nlog target if it matches the default instance as two exceptionless client instances will be created (when the default should be reused).

@snakefoot thanks for this information, would you mind submitting a pr for all this, it would help out a lot.

**Comment by snakefoot** [comment]
Created #299

**Comment by niemyjski** [comment]
Awesome Thanks!, I've left some comments on #299
