### ISSUE TITLE
Generated referenceIds aren't sent to the collector

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.Net#31]
See testcase in https://github.com/exceptionless/Exceptionless.Net/pull/29

The problem is that Event is serialized to the queue path on disk using `ExceptionlessContractResolver`, then during processing it gets deserialized using `DefaultContractResolver` that doesn't know how to deserialize `reference_id`.

**Comment by niemyjski** [comment]
@ejsmith, can you quickly review this as well. I don't see any issues that stand out to me if we applied this fix.

**Comment by ejsmith** [comment]
I think it should be good.

**Comment by niemyjski** [comment]
@srijken can you please verify that this has been fixed in the latest package (3.1.1367). If it's not please comment and I'll reopen this issue.
