### ISSUE TITLE
How can we acces log via .net client

### ISSUE THREAD

**Issue by cetins32** [exceptionless/Exceptionless.Net#313]
We use .net client and we want to show log from  own portal UI
How can we acces log via .net client with tag or with log id etc.   ?

**Comment by cetins32** [comment]
"We want to display events sent to the Self hosted Exceptionless server using a .NET client on our custom-built portal. Is this possible?"

**Comment by niemyjski** [comment]
Yes, but you'd need to use our api to get events using a user scoped token. Please see our docs for how to use our api. https://exceptionless.com/docs/api/api-getting-started/

This client is only for event submission. I'm going to close this as resolved. But please let us know if you have any additional questions.

**Comment by cetins32** [comment]
Thank you for your answer. We will develop our own client to get the event log.

**Comment by niemyjski** [comment]
I'd recommend just making an http client call to get it or generating it via open api.
