### ISSUE TITLE
Persistent 404 Error Logs for "service-worker.js"

### ISSUE THREAD

**Issue by luis-fss** [exceptionless/Exceptionless.Net#314]
I am encountering a recurring issue with Exceptionless.Net within my dotnet 8 Blazor Web App configured for InteractiveServer. The Exceptionless.Net is repeatedly sending more than 150 error logs for "404 /service-worker.js." in the last 3 days.

Despite diligent efforts to identify the root cause, I have been unsuccessful. My project incorporates various logging mechanisms, including file and console logging, among others. However, none of these mechanisms report the "404 /service-worker.js" error. Notably, the browser console also remains silent about this issue, and inspection of the Network tab reveals no related errors.

In an attempt to mitigate the problem, I created a dummy file named "service-worker.js" at the root of the project. Remarkably, this action appears to have resolved the matter, as I no longer observe error logs for this specific issue in Exceptionless.

![image](https://github.com/exceptionless/Exceptionless.Net/assets/685069/1bfb6a57-882c-446f-9664-e35e4bcc9be9)

![image](https://github.com/exceptionless/Exceptionless.Net/assets/685069/723f14d3-8b6e-4a0f-a48a-c220d3ab7a36)

**Comment by niemyjski** [comment]
What is the submission method? If you can reproduce locally you could add an onsubmitting client event handler or plugin and set a breakpoint and look at the call stack.

**Comment by luis-fss** [comment]
I'm not sure I understand what you suggested, but there is no submission method, it's a Blazor Server project. I'm still trying to investigate, but I have no idea who is responsible for calling the "service-worker.js" file, as I said before this file is not even necessary for my project and creating a dummy seems to have resolved the Exceptionless 404 logs without any side effects.

If you have any ideas on how I could track this down I'll be happy to try.

Also, as I found a workaround, I consider that this issue can be closed if you prefer.

**Comment by niemyjski** [comment]
Submission method is sometimes displayed in the ui where it says what event handler submitted the exception). You could wire up a plugin and set a breakpoint in the plugin to see what is generating this error: https://exceptionless.com/docs/clients/dotnet/plugins/ We also have a blazor sample app in this repo that you could try updating until it gets this error and we can debug it as well.

**Comment by niemyjski** [comment]
Looking at the Blazor issues / docs, this seems like it's a generated JavaScript file, you might want to make sure it's getting copied correctly / generated.

**Comment by niemyjski** [comment]
Looking at the Blazor issues / docs, this seems like it's a generated JavaScript file, you might want to make sure it's getting copied correctly / generated.

**Comment by niemyjski** [comment]
I'm going to close this, please let us know if we need to reopen.
