### ISSUE TITLE
Unable to add plugin to MVC app

### ISSUE THREAD

**Issue by paranoid-android** [exceptionless/Exceptionless.Net#35]
I am trying to include a plugin for use within my ASP.NET MVC app. In an attempt to do this, I reviewed this [blog post](http://exceptionless.com/how-to-add-a-plugin-to-affect-events-in-exceptionless/) and this [sample](https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Samples/SampleConsole/Program.cs). When I run my app, it shows my plugin is registered. However, the breakpoint never gets tripped. I have the following:

*Global.asax*
```
protected void Application_Start()
{
  ExceptionlessClient.Default.Configuration.AddPlugin<MyEventPlugin>();
}
```
*MyEventPlugin.cs*
```
    public class MyEventPlugin : IEventPlugin
    {
        [Priority(1000)]
        public void Run(EventPluginContext context)
        {
            context.Cancel = true;                                  // I set a breakpoint on this line.
            throw new NotImplementedException();
        }
    }
```

Finally, in an effort to test my plugin, I have the following:
*HomeController.cs*
public class HomeController : Controller
{
  public ActionResult Test()
  {
    try
    {
      int i = 1;
      i = i / 0;
    } 
    catch (Exception ex)
    {
      foreach (var plugin in Exceptionless.ExceptionlessClient.Default.Configuration.Plugins)
      {
        var pluginName = plugin.Key;
        // Via a breakpoint, on the next line, I can see MyEventPlugin is included.
        Console.WriteLine(pluginName);
      }

     // When the following line is executed, the Run method in MyEventPlugin never gets executed. I am stating this because the breakpoint does not get fired.
     ex.ToExceptionless().Submit();
  }
  return View();
}

What am I missing?

**Comment by niemyjski** [comment]
It looks like everything is good in the code you pasted. I'll try to reproduce first thing in the morning. What version of MVC/.NET are you targeting?

**Comment by paranoid-android** [comment]
@niemyjski ASP.NET MVC 5.2.2.0.  Runtime: v4.0.30319. Thank you for looking into this. I've been banging my head against the wall on it.

**Comment by niemyjski** [comment]
@paranoid-android I've been unable to reproduce this issue

![image](https://cloud.githubusercontent.com/assets/1020579/8555389/7154c9aa-24b5-11e5-93bc-0ebbfe51916d.png)

Is there any chance you can join our [gitter chat room](https://gitter.im/exceptionless/Discuss) and we can setup a remote meeting so I can take a closer look.

**Comment by paranoid-android** [comment]
I was able to get it working after I created a brand new project. I'm still not sure what the issue was. Either ay, there does not seem to be an actual issue with Exceptionless.

**Comment by niemyjski** [comment]
@paranoid-android, But are you still seeing this in your production app? If so, can you try taking a copy of that app and trim everything but that page and keep trimming until it's a basic sample. If you could then attach that sample, that would be a huge help.
