### ISSUE TITLE
Add additional logging when an error occurs while submitting an event.

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#4]
You currently do not know why an event was not submitted. The only message you get is from the AggregateException.

```
DefaultEventQueue: An error occurred while submitting events: One or more errors occurred. 
ExceptionlessClient: Suspending processing for: 00:05:00. 
```

**Comment by Matthew-Davey** [comment]
Even with this fix in place, submission errors are still virtually impossible to troubleshoot. A couple of errors I've had today:

`DefaultEventQueue:An error occurred while submitting events: A task was canceled.`

`DefaultEventQueue:An error occurred while submitting events: Error: SendFailure (Error writing headers)`

**Comment by niemyjski** [comment]
@Matthew-Davey what platform is this on and against managed or self hosted service? Are there any more logs? Would you be willing to submit a pr for better logging around this?

**Comment by Matthew-Davey** [comment]
Hi @niemyjski, here's a more complete log:

```
Jan 04 11:46:11 ﻿Exceptionless|DuplicateCheckerPlugin:Checking event:  with hash: -1194648507
Jan 04 11:46:12 ﻿Exceptionless|DuplicateCheckerPlugin:Enqueueing event with hash: -1194648507 to cache.
Jan 04 11:46:12 ﻿Exceptionless|ExceptionlessClient:Submitting event: type=error
Jan 04 11:46:13 ﻿Exceptionless|DefaultEventQueue:Processing queue...
Jan 04 11:46:14 ﻿Exceptionless|DefaultEventQueue:An error occurred while submitting events: Error: SendFailure (Error writing headers)
Jan 04 11:46:14 ﻿Exceptionless|DefaultEventQueue:Suspending processing for: 00:05:00.
```

This is running on Mono 4.2 on CentOS 6.9 boxes, trying to submit to https://collector.exceptionless.io

It was pretty painful just to get that much logging output, as there appears to be a bug when calling `ExceptionlessClient.Configuration.UseLogger(IExceptionlessLog)` which means it can never have any `MinimumLogLevel` other than INFO - I'll write that up as a separate issue

Anyway, we're pretty stumped. I thought it might be a certificate issue whilst establishing the https connection, but the problem persists even after ensuring all the ca certs were imported into the certificate store. We ran a curl request against the API from one of the boxes, so we know it's not a firewall issue. In any case, with the limited logs we have we can only guess.

I think we're cutting our losses with Exceptionless so I'm not sure I'll be able to spend any more time with it after today.

**Comment by niemyjski** [comment]
:(  Looks like there is a lot of issues out there for mono and this exactly this issue: https://www.google.com/search?q=%22SendFailure+(Error+writing+headers)%22+mono&rlz=1C5CHFA_enUS720US720&oq=%22SendFailure+(Error+writing+headers)%22+mono&aqs=chrome..69i57j0.436j0j4&sourceid=chrome&ie=UTF-8

I wonder curl needs to be updated, updating to .net core would solve many issues here (I'm guessing). What package version are you using (latest pcl or netstandard package?). Yes, please let me know what error you are getting with client logging.

One thing you could try is to copy the following implementation of the submission client and turn off cert validation completely and try running your own copy by registering it into our DI (configuration.resolver) : https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Exceptionless/Submission/DefaultSubmissionClient.cs#L124-L132 Also you could try changing the server url to http instead of https (generally not recommended but worth a try).

If you need any assistance please let me know.

**Comment by Matthew-Davey** [comment]
Hi @niemyjski 

I was able to spend a little more time on this over the weekend, I belive I've gotten to the bottom of the specific issue I was facing. It's unrelated to logging so I wont go into too much detail here (I'll open another issue), however the lack of detailed logging did make it harder to troubleshoot.

**Comment by niemyjski** [comment]
I'll work on adding more logging around this area.

**Comment by Matthew-Davey** [comment]
No worries! I had a very quick look at the code, it looks like it would be worthwhile adding an `Exception` property to [`SubmissionResponse`](https://github.com/exceptionless/Exceptionless.Net/blob/7d7c11cf3ccc641c1b5fd046da7a84a7f638e3b3/src/Exceptionless/Submission/SubmissionResponse.cs#L29), along with the `StatusCode` and `Message` properties. This new property could be populated for example in [`DefaultSubmissionClient.cs#42`](https://github.com/exceptionless/Exceptionless.Net/blob/7d7c11cf3ccc641c1b5fd046da7a84a7f638e3b3/src/Exceptionless/Submission/DefaultSubmissionClient.cs#L42), where currently the exception detail is lost. Finally, in [`DefaultEventQueue.cs#111`](https://github.com/exceptionless/Exceptionless.Net/blob/7d7c11cf3ccc641c1b5fd046da7a84a7f638e3b3/src/Exceptionless/Queue/DefaultEventQueue.cs#L111) you can call the `_log.Error` overload which accepts an Exception argument, which is now accessible from the response.

**Comment by niemyjski** [comment]
@Matthew-Davey Looks like we addressed all of this in the latest versions of the client. I checked and we are flowing all of this information through.
