### ISSUE TITLE
Data Exclusions ignored within ToErrorModelExtensions

### ISSUE THREAD

**Issue by malvada** [exceptionless/Exceptionless.Net#45]
Data Exclusions configured within the project or the client are being ignored within [ToErrorModelExtensions] (https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Extras/Extensions/ToErrorModelExtensions.cs) on line 60.

We add some additional information to our exceptions that are useful on our client exception handling code but useless when reporting the exception.

**Comment by niemyjski** [comment]
Yeah, I could see wanting to exclude certain exception properties (in the case of EF exceptions adding garbage). Would you be willing to submit a pull request for this (please note that there is two versions of ToErrorModelExtensions).

On a side note, not sure if you knew this but if you are viewing a source code on github. If you click on the line of code it will update the url with the line number selected. (I found this one day and use it all the time now :D).

**Comment by malvada** [comment]
Thanks! Did not know about the line-link feature. 

Will submit a pull request for this tomorrow when I am back in office.

**Comment by niemyjski** [comment]
@malvada were you able to do a pull request for this?

**Comment by ejsmith** [comment]
@malvada would love for you to take a stab at this. We could use some help. :-)
