### ISSUE TITLE
Serializer for add object is removing all null fields.

### ISSUE THREAD

**Issue by jamierushton** [exceptionless/Exceptionless.Net#47]
When submitting an object to Exceptionless, all my null fields are removed from the JSON output.

**Comment by niemyjski** [comment]
I'm marking this as a bug as you could want default fields for add object and set property. For example in the following use case no properties will be included as they are all the default values.

```csharp
            try {
                string text = File.ReadAllText("blah.txt");
            } catch (Exception ex) {
                ex.ToExceptionless().AddObject(new TestClass { StringProperty = null, BoolProperty = false, TestClassProperty = null}).Submit();
            }
     
    public class TestClass {
        public string StringProperty { get; set; }
        public bool BoolProperty { get; set; }
        public TestClass TestClassProperty { get; set; }
    }
```

**Comment by niemyjski** [comment]
@ejsmith what are your thoughts on this one?

**Comment by ejsmith** [comment]
We remove them to try and reduce the size of the data being sent to the server since there is always a bunch of things that are not populated, but I guess it sucks that the values don't show up in the UI as being empty. I guess we should stop removing default values.

**Comment by niemyjski** [comment]
yeah, I agree

**Comment by ejsmith** [comment]
Plus we are using compression so it shouldn't be a huge deal. Let's make this change.

**Comment by jamierushton** [comment]
What ever came of this?  Can/should the ticket be closed?

**Comment by niemyjski** [comment]
@jamierushton We upgraded the serializer just recently to the latest version but haven't made this change, we needed to update quite a few tests. Would you be willing to submit a pr for this?

**Comment by jamierushton** [comment]
I've cloned the repo, but I've never submitted anything to OS before.  So I'm finding out what I need to do.

**Comment by niemyjski** [comment]
You should just have to fork the repo and then clone the fork. Then run the serialization unit tests in the tests project. Then just tweak the serialization settings and run/fix the tests that are expecting it to be removed and commit them, once committed you can just click the create pull request button in GitHub :)
