### ISSUE TITLE
Feature request: OnSended event (WPF)

### ISSUE THREAD

**Issue by Stojo303** [exceptionless/Exceptionless.Net#49]
When a user have submitted an issue from the submission dialog, it would be great to have an event so that the app can decide (for example) weather the applications execution should continue or if it should terminate.

Thanks in advance :)

**Comment by niemyjski** [comment]
I don't think we should do an OnSended event but an OnQueued event that happens right after the event has been queued. This will allow you to exit or or process queue and then exit. By default the queue will be processed on wpf when the applications exists.

I think the handler should be something like this:

```csharp
OnQueued(IEnumerable<EventContexts> contexts)
```

This way you could see what was queued and take the proper action with the proper queue / client.

@ejsmith thoughts?

**Comment by niemyjski** [comment]
I've created a pull request here: https://github.com/exceptionless/Exceptionless.Net/pull/51 Your feedback would be greatly appreciated.

**Comment by niemyjski** [comment]
I'm not 100% sure if I'm happy with the way things are named. To me it gives the impression that the event has been sent to the server when it's just been queued (could even be an in memory queue). This event would allow people to close the application (WPF) if needed after an unhandled error.

**Comment by niemyjski** [comment]
This has been fixed in pull request #51 and has been pushed: `3.1.1405`

**Comment by niemyjski** [comment]
You'd just need to wire up to OnSubmitted Event handler and check the property to see if it's unhandled. If it is, close the application.
