### ISSUE TITLE
ExceptionlessClient.Default.Register() throws a TypeInitializationException on machines with .NET Framework 4.0 Client Profile only

### ISSUE THREAD

**Issue by wgraham17** [exceptionless/Exceptionless.Net#5]
It appears that the .NET PCL library fails to load (cannot find System.Core 2.0.5.0) on machines with .NET Framework 4.0 Client Profile installed

Stack trace:

Framework Version: v4.0.30319 
Description: The process was terminated due to an unhandled exception. 
Exception Info: System.TypeInitializationException 
Stack:
Server stack trace: 
at TinyIoC.TinyIoCContainer..ctor() 
at Exceptionless.ExceptionlessClient..ctor() 
at Exceptionless.ExceptionlessClient.<.cctor>b__d() 
at System.Lazy\`1.CreateValue() 
at System.Lazy\`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_Value() 
at Exceptionless.ExceptionExtensions.ToExceptionless(System.Exception, Exceptionless.Enrichments.ContextData, Exceptionless.ExceptionlessClient) 
at Celavimus.Client.ApplicationBootstrapper.AttemptToStartClient() 
at Celavimus.Client.ApplicationBootstrapper.Main(System.String[])

Based on [this blog post](http://www.hanselman.com/blog/FixingSystemCore205FileLoadExceptionPortableLibrariesAndWindowsXPSupport.aspx) it appears to be related to PCLs.

**Comment by niemyjski** [comment]
I need to fire up a clean Windows 7 box and do all the updates (minus .NET 4.5.x) and see if I can reproduce.

**Comment by niemyjski** [comment]
We should also look into replacing the DI system at launch if we are using the full runtime.

**Comment by niemyjski** [comment]
Regardless, we shouldn't ever crash. The app should just disable itself.

**Comment by niemyjski** [comment]
Are you still seeing this behavior or does it go away when you install the patch?

**Comment by niemyjski** [comment]
I've added this to our roadmap. We will be fixing this issue soon. Thank you for your pull request it is greatly appreciated ( https://github.com/exceptionless/Exceptionless/blob/master/README.md )

**Comment by niemyjski** [comment]
Could you please help us do some testing of this change by testing the following packages by pulling the nightly build (3.0.1343 or newer) package from our nightly NuGet feed: https://www.myget.org/F/exceptionless/api/v2

We just need to verify that if you are using pcl then the pcl package is used.. otherwise it's referenced from the NET40/45 packages folder. Lastly it works and doesn't blow up :).

**Comment by niemyjski** [comment]
Please try this feed: https://www.myget.org/gallery/exceptionless

**Comment by niemyjski** [comment]
We are in the process of pushing [v3.1.0](https://github.com/exceptionless/Exceptionless.Net/releases/tag/v3.1.0) out to NuGet!
