### ISSUE TITLE
Use Isolated Storage by default

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#58]
Currently isolated storage is not used by default because the registration exists.

I propose we move use isolated storage to the Startup call. The downside of this is what happens if you want to use in memory storage.. you now have to call that call after the startup call. Also, there is no retry or fallback logic in case isolated storage doesn't work (we know there are some issues with this on some machines a long time ago).

@ejsmith  thoughts?

**Comment by ejsmith** [comment]
We made this decision on purpose for performance reasons. Most people would be ok with a slight risk of losing an event vs slowing their app down.

**Comment by niemyjski** [comment]
So the following code should be removed then? https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Extras/Extensions/ExceptionlessExtraConfigurationExtensions.cs#L66-L67

**Comment by ejsmith** [comment]
Yeah, I am thinking so. I feel like the in memory queue will be fine for most people, but it does kind of suck to have to opt in to offline support. Need to think about this some more.

**Comment by niemyjski** [comment]
Just let me know.

**Comment by niemyjski** [comment]
I added an offline section to the wiki and I'm going to close this issue:

https://github.com/exceptionless/Exceptionless.Net/wiki/Configuration#offline-storage
