### ISSUE TITLE
Nancy exception

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.Net#59]
ExceptionlessClient.Default.RegisterNancy(pipelines);

 Exception Details: System.MissingMethodException: Method not found: 'Nancy.ErrorPipeline Nancy.ErrorPipeline.op_Addition(Nancy.ErrorPipeline, System.Func`3<Nancy.NancyContext,System.Exception,Nancy.Response>)'.

This happens with latest version of Nancy (1.3) and latest Exceptionless on NuGet.

**Comment by Phyxion** [comment]
https://github.com/NancyFx/Nancy/commit/83e115ab237cb0fccd9fd289dfb29ab95897a076

Didn't really check further but it's probably related to this commit.

**Comment by niemyjski** [comment]
Thanks for letting us know about this. Is there any chance you could submit a pull request for this?

**Comment by Phyxion** [comment]
Unfortunately, no. I'm going away for a while tomorrow and I won't have access to my normal desktop.

**Comment by niemyjski** [comment]
I think this is fixed in the my latest commit. I think it just need to be recompiled against 1.3. I'll be pushing a new nuget package in a little bit. Please let me know if this doesn't fix this issue.

**Comment by Phyxion** [comment]
Is the NuGet package pushed already? I just got back and can check it out if needed.

**Comment by niemyjski** [comment]
Yes, it's been pushed.

**Comment by Phyxion** [comment]
I'll check it out soon (I hope this week).

**Comment by Phyxion** [comment]
Seems to work again (at least Nancy starts again), didn't receive an exception yet but I assume everything is OK now.

**Comment by niemyjski** [comment]
Please keep me updated

**Comment by Phyxion** [comment]
Took a while to get an exception but it's working :+1:
