### ISSUE TITLE
ExceptionlessClientExtensions.Startup override ISubmissionClient previously set by user

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#6]
Hi,

In the ExceptionlessClientExtensions.Startup method, the default ISubmissionClient is registered even if the user has set a custom ISubmissionClient.

I set my ISubmissionClient before calling client.Register(), so I lost an hour understanding why my ISubmissionClient was not used while submitting events.

It's because Register() --> Startup() override unconditionally the ISubmissionClient:
```c#
client.Configuration.Resolver.Register<ISubmissionClient, SubmissionClient>();
```

Perhaps you could check for already ISubmissionClient registered before registering the default one?

Here is a code showing the issue:
```c#
var config = new ExceptionlessConfiguration(DependencyResolver.Default);
         config.Resolver.Register<ISubmissionClient, MySubmissionClient>();
         config.ApiKey = "BD0A3EDC-CA53-4E1A-A82A-882284A24D4C";

         var client = new ExceptionlessClient(config);
        // ISubmissionClient == MySubmissionClient
         client.Register(); 
         // ISubmissionClient == Exceptionless.Extras.Submission.SubmissionClient
```

**Comment by ejsmith** [comment]
Yeah, I think that would be great. Would you mind submitting a pull request to make that change?

**Comment by CyberSinh** [comment]
The DependencyResolverExtension already use a fallback system to return default IService if one is missing.

```c#
public static ISubmissionClient GetSubmissionClient(this IDependencyResolver resolver) {
            return resolver.Resolve<ISubmissionClient>() ?? resolver.Resolve<DefaultSubmissionClient>();
        }
```

So, do you know why registering IService in the ExceptionlessClientExtensions.Startup method is required?

```c#
public static void Startup(this ExceptionlessClient client, AppDomain appDomain = null) {
            client.Configuration.Resolver.Register<ISubmissionClient, SubmissionClient>();
            client.Configuration.Resolver.Register<IEnvironmentInfoCollector, EnvironmentInfoCollector>();
// ...
}
```

Thanks

**Comment by niemyjski** [comment]
Because the portable library has very basic implementations while the ones in the startup method in the extras project has a "full" implementation. For example Plc doesn't support proxies or the ability to parse stack traces while the extras ones can. We could argue that we shouldn't be set by default and that the startup method should only set one if one isn't defined

**Comment by niemyjski** [comment]
But I'm not sure what would get resolved if you don't register a default one, the extension methods good for getting an instance but that's never used during object construction

**Comment by ejsmith** [comment]
I think we can not set the default one and then only do a registration if there isn't one defined.

**Comment by CyberSinh** [comment]
Thanks for the precision.
Calling ExceptionlessClient.Default.? is sufficient to register all default services. 
I have just commit a fix in my PR.

**Comment by niemyjski** [comment]
Thanks, I'll take a look into this.

**Comment by niemyjski** [comment]
@CyberSinh Thanks for reporting this issue! Please let me know if you want me to push this fix right away.
