### ISSUE TITLE
Fix CrashReportDialog styling or add dialog provider configuration?

### ISSUE THREAD

**Issue by mgnslndh** [exceptionless/Exceptionless.Net#60]
I am using [MaterialDesignInXamlToolkit](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit) together with Exceptionless and the `CrashReportDialog` does not look OK to me. I guess other themes applied at the application level can cause similar issues.

![image](https://cloud.githubusercontent.com/assets/1139118/10344520/023e8314-6d24-11e5-82ce-29c03c53f100.png)

I have two problems with the look of the `CrashReportDialog` when the material design theme is applied:

1. The buttons use hardcoded width which cause problems with the material design style for buttons. This is  potential problem any style.
2. The `CrashReportDialog` use default styles which are overridden at the application level to use the material design styles. This might be ok for certain styles/themes but for the material design style I think I would like more control to make it look even more "material".

Some suggestions that can be implemented separately or in combination as a solution to the styling issues:

1. Provide `ICrashReportDialog` abstraction and ability to configure a factory. This would allow a developer to provide his own implementation and total control over the user experience.
2. Make sure the `CrashReportDialog` use its own styles for the presentation and does not rely on default styles that can be overriden at application level.

**Comment by niemyjski** [comment]
Yeah, that doesn't look very good.

1. Would you mind submitting a patch for this that makes it behave the same but doesn't use a width.
2. I'm not sure the best thing to do for this. By default we don't hard code any style keys because we want it to pick up themes/be easier to theme. It's been a few years since I styled a third party wpf control, so please let us know if there is anything specifically we can do to make this easier. A pull request after discussion would be greatly appreciated.

---

1. I think it would be good to abstract this behavior as it would allow users to inject custom forms be it windows forms or wpf easier.
2. Please refer to the previous number 2.

**Comment by niemyjski** [comment]
Please let me know what you think.

**Comment by mgnslndh** [comment]
Ok, I'll have a stab at it and see what I can do.

**Comment by niemyjski** [comment]
Thanks! If you need any help please let us know.

**Comment by niemyjski** [comment]
I just made some changes to the dialog for #61 to address a bunch of white space at the bottom of the dialog. I'm also going to push your changes out now.

**Comment by niemyjski** [comment]
@mgnslndh if you want, I'd be more than happy to pair with you on changing how this dialog is shown.

**Comment by mgnslndh** [comment]
I am a bit busy at the moment but I will go back and check out the new release. I have also noticed that the dialog style is broken again because of updates in [MaterialDesignInXamlToolkit](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit). Perhaps the best solution is to support pluggable dialogs as you suggested.

**Comment by niemyjski** [comment]
Yes, I think that would be a good thing. Currently you can override this dialog completely by passing false to Register() and hooking up the event handlers but we should make this easier.

**Comment by niemyjski** [comment]
@mgnslndh I'm planning on releasing 3.2 very soon. Is there any chance you could send me a pull request with bug fixes.

**Comment by mgnslndh** [comment]
@niemyjski I'm sorry but I do not think I have the time to fix this just. I will have to do something about the issue, just not at this point in time :)

**Comment by niemyjski** [comment]
I'm going to close this issue to help keep the issue list clean. I think this would be really nice to have and would be willing to accept a pr for this.  I think there would be an interface that gets injected and its whole purpose is showing a dialog, and then you can inject your own.

**Comment by niemyjski** [comment]
Currently if you'd like to override the title or make extra changes, you'd need to source import the code for this and then pass false to the Register call to not show the dialog, then wire up your own as shown here (https://github.com/exceptionless/Exceptionless.Net/blob/master/src/Platforms/Exceptionless.Wpf/ExceptionlessWpfExtensions.cs#L49-L58)
