### ISSUE TITLE
readme.txt epansion

### ISSUE THREAD

**Issue by gr0ss** [exceptionless/Exceptionless.Net#64]
As a noob coder loading Exceptionless.Windows into my project for the first time...

readme.txt showing up right on the load of the nuget package was awesome, and the text reads really well, easy to follow, but....

Right after the initial setup, I want a link to take me to more small examples on how to set up the cool implementations of your project like Blake showed me in a demo.  Just small things so as a visual learner, I can jump right in to catching exceptions the way I want to, setting up user recording, adding variables to set on my dashboard and the implementation of that in my code.

**Comment by niemyjski** [comment]
Thanks for your suggestion. I've updated the read me with a link to sample usages!
