### ISSUE TITLE
Request Info Cookie names are being changed by the serializer

### ISSUE THREAD

**Issue by skoub** [exceptionless/Exceptionless.Net#68]
a cookie name *lastLogin* is replaced with *last_login*. It should keep the original value as is.

**Comment by niemyjski** [comment]
I'm closing this as a duplicate of I'm closing this as it's a duplicate of https://github.com/exceptionless/Exceptionless.Net/issues/63 Is there any chance you could help us by taking a look our our serializer settings.

**Comment by niemyjski** [comment]
A new version of the client is being pushed that fixes this issue.
