### ISSUE TITLE
Request Info Post Data parameter names are being changed by the serializer

### ISSUE THREAD

**Issue by skoub** [exceptionless/Exceptionless.Net#69]
When you submit a form (HttpPost), the parameter names are changed. For example, the parameter name *demandeInfo[actionIds][]* is changed for *Demande info[action ids][]*.

**Comment by niemyjski** [comment]
I'm closing this as a duplicate of I'm closing this as it's a duplicate of https://github.com/exceptionless/Exceptionless.Net/issues/63 Is there any chance you could help us by taking a look our our serializer settings.
