### ISSUE TITLE
Add support for X-Forwarded-For header

### ISSUE THREAD

**Issue by ejsmith** [exceptionless/Exceptionless.Net#77]
Adding support for this will help with proxy servers and would enable us to properly identify individual users. Should at least make sure this is going to the server side to be analyzed there.

**Comment by ejsmith** [comment]
https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by niemyjski** [comment]
What would we need to set this to?

**Comment by niemyjski** [comment]
We need to finish adding support for the other clients before we merge this into master

**Comment by niemyjski** [comment]
We need to ensure we are removing the port from the IP address. I came across a use case where the port was submitted.

**Comment by ejsmith** [comment]
Make sure that we don't lose any information though. So we shouldn't just be throwing the port away.

**Comment by niemyjski** [comment]
We have to parse it correctly server side for geo ip lookup then, it's currently failing
