### ISSUE TITLE
source in CreateLog

### ISSUE THREAD

**Issue by ahmettaha** [exceptionless/Exceptionless.Net#78]
Hello,

Why is the source parameter required with the CreateLog method if I want to send a LogLevel also. I see that there is an override, if I dont provide LogLevel, but there is no method signature like below. I'm sending null for source for now. is this a problem?
`
CreateLog(this ExceptionlessClient client, string message, LogLevel level);
`

**Comment by ejsmith** [comment]
Yeah, there really isn't any reason why source should be necessary. Guessing that using null for source works fine, right?  If so, then I guess we just need an extension method with that signature. Can you submit a pull request for that?

**Comment by ahmettaha** [comment]
is it possible that "most frequent" table to group with source and "most recent" to group by message. that's what it looks like. I'm sending null as source, and "(global)" is displayed in "most frequent"

**Comment by niemyjski** [comment]
Most frequent is a stack (of events) and most recent is the actual event. If you send in null for source, than it will be put into a global stack. as logs are stacked on source (where they came from). Typically this should be set. @ejsmith I wonder if we can set it to member caller attributes on > .NET 4.5

**Comment by ahmettaha** [comment]
If you could do that. It would be great.

**Comment by niemyjski** [comment]
@ahmettaha would you mind submitting a pull request for the overload that doesn't take source.

**Comment by ahmettaha** [comment]
i think the library is targeting .net 4. I couldnt use caller attributes. So I couldnt create a pull request. I'm just going to add to my own project for now. thank you

**Comment by niemyjski** [comment]
It's fine, I think we still need an overload that takes the message and loglevel, would you mind submitting this. We can worry about the member caller attributes later :)

**Comment by ahmettaha** [comment]
I have create a pull request.

https://github.com/exceptionless/Exceptionless.Net/pull/79

**Comment by niemyjski** [comment]
Awesome thanks a ton! This change will go out today!

**Comment by niemyjski** [comment]
https://github.com/exceptionless/Exceptionless.Net/releases/tag/v3.3.4 This has also been pushed to NuGet.
