### ISSUE TITLE
Add expander showing actual Exception

### ISSUE THREAD

**Issue by azchrisf** [exceptionless/Exceptionless.Net#8]
It would be great to have an expander button (either horizontal or vertical, vertical being proffered) that would expand the dialog and show the actual Exception that occurred in a read-only textbox.

This could include additional info such as Date/Time, machine name, etc.

This would be good for advanced and curious users.

**Comment by niemyjski** [comment]
I think we should also have something like this. I think it would be good to show off all data that will be sent. Would you mind submitting a pull request for this? I think we should have a link button (click here to see...) and it shows a dialog with the content being sent.

**Comment by azchrisf** [comment]
I'd love to help but I'm not a C# programmer, I do VB.NET. :-)
This seems like something that could be done in 15 minutes, I can give it a shot using a VB -> C# converter if you tell me what the method or property the UI uses to get the actual exception.

**Comment by niemyjski** [comment]
I would just get our serializer (and all config.Resolver.GetJsonSerailizer() https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Shared/Dependency/DependencyResolverExtensions.cs#L61 ) and serialize it to a string and show that content as it's exactly what is sent. I'd add a link to the dialog that says something like Click here to show what's sent and then show the dialog

**Comment by azchrisf** [comment]
I'm not sure how you implement that to get the data - I'm going to leave that department to you guys as you're more familiar with how your app works.

Here is the finished UI code

http://www.cfcsaz.com/personal/Dialog.zip

The only thing left is to populate the textbox with the Crash stack/info - AdditionalErrorInfo.Text
Let me know that snippet so I can throw it in there when your done.

**Comment by niemyjski** [comment]
I've yet to get a chance to look into this, but it's on my task list.

**Comment by niemyjski** [comment]
@xbelt  would you mind attaching a screenshot of the new behavior?

**Comment by xbelt** [comment]
@niemyjski 
Here you go:
closed: 
![closed](http://puu.sh/j74F8/7a664e7864.png)
opened: 
![opened](http://puu.sh/j752u/664baafc2d.png)

**Comment by niemyjski** [comment]
Thanks for the screenshots. Is there any way we can get these updated for wpf as well? @ejsmith thoughts?

**Comment by ejsmith** [comment]
I like it. I think I might prefer that the button showed another dialog with the JSON in it instead of expanding the existing dialog only because it seems like the dialog is already pretty tall and you would also probably want to be able to maximize the window and see all of the JSON easily.  Also would probably be nice to use JSON.NET's formatted version of the JSON so it's a little easier to look at.

**Comment by niemyjski** [comment]
Yeah it might be nice to show a dialog / modal. But I think we need to reuse our serializer incase someone wants to take that and manual submit it via the api..

**Comment by xbelt** [comment]
I will look at it to improve the form. I have never worked with wpf but I will give it a go.

**Comment by ejsmith** [comment]
@niemyjski yeah, I mean our embedded version of the serializer. I am just saying that I would want to be looking at a formatted version of the JSON.

**Comment by xbelt** [comment]
I am sorry that I haven't done any work recently but exams are coming up ;)

**Comment by niemyjski** [comment]
@xbelt were you able to take a look into this? I hope you did well on your exams

**Comment by xbelt** [comment]
@niemyjski Yeah I started quite a while ago but never found enough time for it. I do not think I will be able to actually complete this project in the near future... Sorry about that

**Comment by niemyjski** [comment]
Thanks for the update. Is there anyone who would like to take this over?

**Comment by niemyjski** [comment]
I'm going to close this as it also needs to also support wpf. Please feel free to open a pull request and reference this issue and we'll reopen this issue. Ideally, we'd love if this opened a new dialog or layer ontop of this dialog with the content.
