### ISSUE TITLE
Improve handling of Exception<T> where T : struct

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.Net#83]
@corneliutusnea commented on [Wed Aug 12 2015](https://github.com/exceptionless/Exceptionless/issues/132)

We use an Exception<T> which gets rendered a bit oddly in the UI.
public class CustomException<T> : ApplicationException
where T : struct
We use this so we can use enums instead of strings for error messages that are then easy to group in "buckets" or localize.

The the EL UI they get rendered as:
My.Custom.Namespace..CustomException`1[[Some.Long.Name.Space.ErrorCategory_ErrorBucket, Long.AssemblyName., Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

EL should understand such exceptions and render them as:
CustomException<ErrorCategory_ErrorBucket>

---

@niemyjski commented on [Thu Aug 13 2015](https://github.com/exceptionless/Exceptionless/issues/132#issuecomment-130735046)

Yeah, I agree this should use the namespace+typename and not the assembly full name.

---

@niemyjski commented on [Thu Aug 13 2015](https://github.com/exceptionless/Exceptionless/issues/132#issuecomment-130737151)

It also looks like the grids are having issues with these type names too.

**Comment by niemyjski** [comment]
We need to add tests for this.

**Comment by Jaans** [comment]
Running into this one too :-(

We are having a similar problem with `ServiceModel` exceptions that have generic `Fault<>`types.

If it helps, here's an example of how it presents in the UI:
![image](https://user-images.githubusercontent.com/3510981/72808727-df30a900-3ca5-11ea-9188-f0eeb151e4bd.png)

As you can see it's a bit hard to see what it is without hovering for a tooltip for each one.

**Comment by niemyjski** [comment]
That's not good at all, is there any chance you could add some tests for this or snippet. Looks like we'd just need to update the Error Plugin and how it shreds the error into our model.

**Comment by Jaans** [comment]
Thank you!

This should be enough to get you to repro the behaviour:

```
var exception = new DivideByZeroException("Oops!");
var exceptionDetail = new System.ServiceModel.ExceptionDetail( exception );
var faultException = new System.ServiceModel.FaultException<System.ServiceModel.ExceptionDetail>( exceptionDetail, "Service has failed" );

// Send it to exceptionless
throw faultException;
```

Let me know if you need more info.

**Comment by elachlan** [comment]
Relates to #177

This is still a problem after Demystifier was implemented.
![image](https://user-images.githubusercontent.com/2433737/166574053-028741b0-bdc1-48da-9e44-856ab68ef9da.png)

The error plugin uses `ToErrorModel`
https://github.com/exceptionless/Exceptionless.Net/blob/118b006c1c66c7fcc2c668f91af5a27cad8bd2ab/src/Exceptionless/Plugins/Default/020_ErrorPlugin.cs#L21

Should it being using ToSimpleErrorModel, which makes use of Demystifier?

**Comment by niemyjski** [comment]
Both implementations should use demystify which I don't think would have fixed this issue. We need to better handle this in ToError()

**Comment by elachlan** [comment]
@niemyjski see #272
