### ISSUE TITLE
Wrong os version returned on Windows 10

### ISSUE THREAD

**Issue by CyberSinh** [exceptionless/Exceptionless.Net#89]
Hi,

Exceptionless.Net seems to report 6.2 OS version on Windows 10 machine. Is that normal?

Extract of JSON returned by Exceptionless .NET client (used in a WPF application):
"o_s_name":"Microsoft Windows 10 Home","o_s_version":"6.2.9200.0"

Thanks.

Regards,

Cyber Sinh

**Comment by ejsmith** [comment]
I think that might be right, but I'm not totally sure.

http://arstechnica.com/information-technology/2014/11/why-windows-10-isnt-version-6-any-more-and-why-it-will-probably-work/

**Comment by CyberSinh** [comment]
If that's true, should I consider the "OS Name" more reliable than "OS version" to compute statistics about OS usage?

**Comment by niemyjski** [comment]
Yeah, it probably would be better to use the name as long as it isn't localized. We are just using EnvironmentInformation api to get the os version. It might be worth logging a bug with microsoft on this one.

**Comment by niemyjski** [comment]
We populate it like this: https://github.com/exceptionless/Exceptionless.Net/blob/master/Source/Extras/Services/EnvironmentInfoCollector.cs#L38 could you please research this further and let us know if there is a better way to get the version?

**Comment by CyberSinh** [comment]
Perhaps the issue come from windows targeting issue.

On Windows 8 and 10, you have to target supported windows version in the manifest to get the real version of the OS.

https://msdn.microsoft.com/fr-fr/library/windows/desktop/dn481241(v=vs.85).aspx
http://stackoverflow.com/questions/32336328/targetting-win-10-from-app-manifest-c-sharp/33355377

Hope this helps.

**Comment by niemyjski** [comment]
Should we close this issue? If you are running the .net standard version you will get the correct os version, but if you are using the full framework you will not (because we don't take out a dependency on the new api). Are you aware of any good way to do this on the full framework?

**Comment by CyberSinh** [comment]
Microsoft.VisualBasic.Devices.ComputerInfo.OSVersion gives me the correct version on Windows 10 if I target windows 10 in the manifest with the full framework.

Perhaps you could simply warn developers in the Exceptionless.Net documentation that targeting supported windows in their app.manifest is a require to get reliable OS version information.

**Comment by niemyjski** [comment]
Sure, would you mind adding this to the configuration documentation? I'm going to close this as there is a work around.

**Comment by CyberSinh** [comment]
I would like to help to improve the documentation but I am not sure my English level would be enough. My mother tongue is french.

**Comment by niemyjski** [comment]
If you want to add it here as a comment we could reference this issue or I could rework it into the docs. What ever you feel comfortable doing 👍  (P.S., I thought you were a native english speaker, your english is quite good).
