### ISSUE TITLE
Log4net client does not honor a LevelEvaluator

### ISSUE THREAD

**Issue by kellyelton** [exceptionless/Exceptionless.Net#9]
So inside of a log4net appender you can add something like this

    <appender name="exceptionless" type="Exceptionless.Log4net.ExceptionlessAppender,Exceptionless.Log4net">
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date %-5level %property{version} %property{username} [%thread] %logger - %message%newline %exception"/>
      </layout>
      <evaluator type="log4net.Core.LevelEvaluator">
        <threshold value="INFO"/>
      </evaluator>
    </appender>

The idea is that it will only log things that are equal to or over the `threshold`. Currently it doesn't seem to honor this since it doesn't inherit `BufferedAppenderSkeleton`.

Maybe a nice answer would be a new appender, like `BufferedExceptionlessAppender` ?

**Comment by niemyjski** [comment]
What would the new config look like? Is there any reason you'd want two different appenders? Seems like the buffered would just work all the time. Is there any extra configuration you'd need between the two? Can we tell the buffered one to wait 5 seconds or until you have 5 log messages before you create the log messages?

**Comment by niemyjski** [comment]
Should the readme also be updated to talk about filtering via a threshold?

**Comment by kellyelton** [comment]
The config would be the same except you would specify the buffered appender. Then you would be able to use some other functionality, such as the evaluator or BufferSize etc.

The reason using an evaluator is nice with the buffered appender, is that you can say, "If we get an `error` level event, flush the past X number of log events"...Where as with a standard `threshold` setting, it only sends those that match.

I can see the buffered one being useful as well if you wanted to add a new api call to allow multiple logs at once, maybe reducing the load of logs hitting your/any server.

More info on the buffered appender here http://logging.apache.org/log4net/release/sdk/log4net.Appender.BufferingAppenderSkeleton.html

**Comment by niemyjski** [comment]
We already buffer them via our queue implementation. I'm just wondering if people will find our BufferedAppender if we don't ever mention it. Seems kind of crazy that you can't filter out by log level unless you use a BufferedAppender

**Comment by kellyelton** [comment]
You can filter, it's just with the evaluator, it basically says "Send all previous X log messages if we get triggered by a specific event type, such as an Error"

The nice thing is that instead of only getting ERROR logs, you can get some context, like the DEBUG and INFO and WARNS leading up to it.

**Comment by niemyjski** [comment]
Ah, that makes much more sense.

**Comment by ejsmith** [comment]
It sounds like you are pretty familiar with this area @kellyelton. Do you want to submit a pull request with this change?

https://github.com/exceptionless/Exceptionless.Net/tree/master/Source/Platforms/Log4net
